{
  "hash": "ea139fb539ac3439e07d48e90bbaf050",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Linear Regression with Categorical Variables and ANOVA: Ace Rates in Tennis by Surface\"\nformat: html\ndate: January 22, 2025\ndescription: Using tennis to teach ANOVA and linear regression with categorical variables\neditor: \n  canonical: true\ncategories:\n  - ANOVA\n  - Tennis\noutput: \n  learnr::tutorial:\n    progressive: TRUE\nruntime: shiny_prerendered\n---\n\n\n\n\n\n\n## Welcome\n\nPlease watch this intro video from tennis analyst Dr. Stephanie Kovalchik to learn about the questions we'll be investigating today!\n\n<iframe src=\"https://drive.google.com/file/d/1elu4ZeSGuLIO5AgUnh4nB54btxtPxNkJ/preview\" width=\"640\" height=\"480\" allow=\"autoplay\">\n\n</iframe>\n\n## Background\n\nThis lesson is going to investigate whether ace rates differ across different surfaces in tennis. We will begin by exploring the data and conducting some descriptive analyses and visualizations. Then we will answer our question using linear regression and dummy variables for categorical data.\n\nAnd, in the process, we will learn that analysis of variance (ANOVA) - commonly used to compare means of a continuous variable across three or more groups - is just a special case of linear regression!\n\n### Tennis Basics\n\nIf you are not familiar with tennis, consider watching [this 4-minute introductory video](https://www.youtube.com/watch?v=1P_Das6OjAk).\n\nIn a basic singles match, two players face off against each other on either side of the court, hitting a tennis ball back and forth.\n\nA single tennis **match** is typically split into either 3 or 5 **sets**, and the winner of a majority of the sets wins the match.\n\nEach **set** is split into **games** (or **service games**) - a player must win 6 games and at least 2 more than an opponent *or* win a tiebreak game to win the set.\n\nTo win a game a player must score at least 4 **points** and at least 2 more than their opponent.\n\nEach point starts off with a player **serving** the ball to another by tossing it into the air and hitting it with their racket. The opposing player then tries to return it back to the server's side of the court, and play continues like this until one player fails to legally return the ball. The other player scores a point.\n\nThe player who **serves** switches each **game**, hence the term \"service game.\"\n\n### Surface\n\nIn tennis, the surface refers to the type of court on which the game is played. There are three types of surfaces in professional tennis:\n\n-   **Clay**: Clay courts are made of crushed brick, shale, or stone, and they have a slower pace compared to grass courts. The ball tends to bounce higher on clay, making it favorable for baseline rallies. The French Open is played on clay courts.\n\n-   **Grass**: Grass courts are known for their fast and low-bouncing nature. Wimbledon, one of the most prestigious tennis tournaments, is played on grass courts.\n\n-   **Hard courts**: Hard courts are typically made of asphalt or concrete covered with a top layer of synthetic materials. They offer a medium-paced game and are the most common type of court. The US Open and the Australian Open are played on hard courts.\n\n### Aces\n\nAn **ace** occurs when a player serves the ball and the opponent fails to touch it with their racket, winning an immediate point for the server. Aces are considered a significant achievement for a server.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"panel panel-default tutorial-question-container\">\n<div data-label=\"ace_rate_q\" class=\"tutorial-question panel-body\">\n<div id=\"ace_rate_q-answer_container\" class=\"shiny-html-output\"></div>\n<div id=\"ace_rate_q-message_container\" class=\"shiny-html-output\"></div>\n<div id=\"ace_rate_q-action_button_container\" class=\"shiny-html-output\"></div>\n<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>\n</div>\n</div>\n```\n\n:::\n:::\n\n\n\n\nAce rate, defined as the number of aces per service game, will be our main outcome. We will create it below.\n\n## Data Exploration and Descriptive Analysis\n\nBelow is the data from all 2023 Association of Tennis Professionals (ATP) tour-level main draw matches. This is the top-tier men's tennis tour.\n\nThe original data was sourced from a Github repository by Jeff Sackmann and Tennis Abstract: <https://github.com/JeffSackmann/tennis_atp>. Its formatting has been modified somewhat for this tutorial.\n\nLet's begin by exploring the data. The data is stored in a table called `match2023_df`.\n\n\n\n\n::: {.cell exercise='true' exercise.eval='false'}\n<div class=\"tutorial-exercise\" data-label=\"head\" data-completion=\"1\" data-diagnostics=\"1\" data-startover=\"1\" data-lines=\"0\" data-pipe=\"|&gt;\">\n\n```{.r .cell-code}\n# Print the (first 1000 rows of) the data\nmatch2023_df\n\n# Get a summary of the data\nsummary(match2023_df)\n```\n\n<script type=\"application/json\" data-ui-opts=\"1\">{\"engine\":\"r\",\"has_checker\":false,\"caption\":\"<span data-i18n=\\\"text.enginecap\\\" data-i18n-opts=\\\"{&quot;engine&quot;:&quot;R&quot;}\\\">R Code<\\/span>\"}</script></div>\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"panel panel-default tutorial-question-container\">\n<div data-label=\"rows\" class=\"tutorial-question panel-body\">\n<div id=\"rows-answer_container\" class=\"shiny-html-output\"></div>\n<div id=\"rows-message_container\" class=\"shiny-html-output\"></div>\n<div id=\"rows-action_button_container\" class=\"shiny-html-output\"></div>\n<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>\n</div>\n</div>\n```\n\n:::\n:::\n\n\n\n\nGiven that each row represents a match, based on the previous terminology, can you guess what each of these columns represents?\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"panel panel-default tutorial-question-container\">\n<div data-label=\"logicals1\" class=\"tutorial-question panel-body\">\n<div id=\"logicals1-answer_container\" class=\"shiny-html-output\"></div>\n<div id=\"logicals1-message_container\" class=\"shiny-html-output\"></div>\n<div id=\"logicals1-action_button_container\" class=\"shiny-html-output\"></div>\n<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>\n</div>\n</div>\n```\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"panel panel-default tutorial-question-container\">\n<div data-label=\"logicals2\" class=\"tutorial-question panel-body\">\n<div id=\"logicals2-answer_container\" class=\"shiny-html-output\"></div>\n<div id=\"logicals2-message_container\" class=\"shiny-html-output\"></div>\n<div id=\"logicals2-action_button_container\" class=\"shiny-html-output\"></div>\n<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>\n</div>\n</div>\n```\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"panel panel-default tutorial-question-container\">\n<div data-label=\"logicals3\" class=\"tutorial-question panel-body\">\n<div id=\"logicals3-answer_container\" class=\"shiny-html-output\"></div>\n<div id=\"logicals3-message_container\" class=\"shiny-html-output\"></div>\n<div id=\"logicals3-action_button_container\" class=\"shiny-html-output\"></div>\n<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>\n</div>\n</div>\n```\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"panel panel-default tutorial-question-container\">\n<div data-label=\"logicals4\" class=\"tutorial-question panel-body\">\n<div id=\"logicals4-answer_container\" class=\"shiny-html-output\"></div>\n<div id=\"logicals4-message_container\" class=\"shiny-html-output\"></div>\n<div id=\"logicals4-action_button_container\" class=\"shiny-html-output\"></div>\n<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>\n</div>\n</div>\n```\n\n:::\n:::\n\n\n\n\n### Calculate Ace Rate\n\nRemember what we said above about simply looking at the number of aces in a match being insufficient? It is easy to get more aces if the match is longer (that is, there are more service games). We can look at the data to verify our hypothesis:\n\n\n\n\n::: {.cell exercise='true'}\n<div class=\"tutorial-exercise\" data-label=\"plot1\" data-completion=\"1\" data-diagnostics=\"1\" data-startover=\"1\" data-lines=\"0\" data-pipe=\"|&gt;\">\n\n```{.r .cell-code}\nggplot(match2023_df, aes(x = total_ServiceGames, y = total_aces)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"blue\") +\n  labs(x = \"Service Games in Match\", y = \"Aces in Match\") +\n  ggtitle(\"Association Between Number of Aces and Service Games in Tennis Matches\")\n```\n\n<script type=\"application/json\" data-ui-opts=\"1\">{\"engine\":\"r\",\"has_checker\":false,\"caption\":\"<span data-i18n=\\\"text.enginecap\\\" data-i18n-opts=\\\"{&quot;engine&quot;:&quot;R&quot;}\\\">R Code<\\/span>\"}</script></div>\n:::\n\n\n\n\nThere indeed is a positive association between winner's number of ace and winner's service games.\n\nSince some surfaces lend themselves to longer matches than others we need to adjust for match length so that any differences we see are more likely due to the surfaces themselves rather than the fact that longer matches are played on them.\n\nTo do this we calculate **ace rate**, which we define as the number of aces divided by the number of service games in a match.\n\n$$ace\\_rate = \\frac{total\\_aces}{total\\_ServiceGame}$$\n\nHere is some code to create that variable:\n\n\n\n\n::: {.cell exercise='true'}\n<div class=\"tutorial-exercise\" data-label=\"ace_rate\" data-completion=\"1\" data-diagnostics=\"1\" data-startover=\"1\" data-lines=\"0\" data-pipe=\"|&gt;\">\n\n```{.r .cell-code}\n match2023_df <- match2023_df %>%\n    mutate(ace_rate = total_aces/total_ServiceGames)\n\n# Look at the first 6 rows of the data with the new variable\nhead(match2023_df)\n```\n\n<script type=\"application/json\" data-ui-opts=\"1\">{\"engine\":\"r\",\"has_checker\":false,\"caption\":\"<span data-i18n=\\\"text.enginecap\\\" data-i18n-opts=\\\"{&quot;engine&quot;:&quot;R&quot;}\\\">R Code<\\/span>\"}</script></div>\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\nIdeally we would have used the number of aces per serve, because if the number of serves per service game differs by surface that could explain any differences we observe in our measure of ace rate. For a simple if unrealistic example, say there are 10 serves per service game on clay versus 20 serves per service game on hard court and grass. Even if exactly 20% of serves are aces on each surface, we would observe an ace rate *per service game* of 2.0 for clay and 4.0 for hard court and grass. This difference would appear even though the chance of any given serve being an ace doesn't vary by surface.\n\nUnfortunately our data does not have the number of serves so we will have to continue with this limitation.\n\n### Ace Rate by Surface\n\nWe can finally look into how aces vary across the three types of tennis surfaces. We should begin by investigating the distribution of ace rate in matches on each type of surface. A good place to start is with boxplots, which the code below will create for us:\n\n\n\n\n::: {.cell exercise='true' exercise.setup='ace_rate_for_exer'}\n<div class=\"tutorial-exercise\" data-label=\"mean_and_boxplots\" data-completion=\"1\" data-diagnostics=\"1\" data-startover=\"1\" data-lines=\"0\" data-pipe=\"|&gt;\">\n\n```{.r .cell-code}\n# Get average overall ace rate\nmean_acerate <- mean(match2023_df$ace_rate, na.rm = TRUE)\n\n# Create boxplots with overall mean ace rate as red line\nggplot(match2023_df, aes(x = surface, y = ace_rate)) +\n  geom_boxplot() +\n  labs(title = \"Ace Rate by Surface Type\",\n       x = \"Surface Type\",\n       y = \"Ace Rate\",\n       caption = \"Red line is overall mean ace rate across all surfaces.\") +\n  geom_hline(yintercept = mean_acerate, linetype = \"dashed\", color = \"red\")+\n  theme_minimal()+\n  scale_y_continuous(limits = c(0, 0.75), breaks = seq(0, 0.75, by = 0.25))\n```\n\n<script type=\"application/json\" data-ui-opts=\"1\">{\"engine\":\"r\",\"has_checker\":false,\"caption\":\"<span data-i18n=\\\"text.enginecap\\\" data-i18n-opts=\\\"{&quot;engine&quot;:&quot;R&quot;}\\\">R Code<\\/span>\"}</script></div>\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"panel panel-default tutorial-question-container\">\n<div data-label=\"surf_diff\" class=\"tutorial-question panel-body\">\n<div id=\"surf_diff-answer_container\" class=\"shiny-html-output\"></div>\n<div id=\"surf_diff-message_container\" class=\"shiny-html-output\"></div>\n<div id=\"surf_diff-action_button_container\" class=\"shiny-html-output\"></div>\n<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>\n</div>\n</div>\n```\n\n:::\n:::\n\n\n\n\nLet's now calculate the three means and medians for each surface to further show the difference.\n\n\n\n\n::: {.cell exercise='true' exercise.setup='ace_rate_for_exer'}\n<div class=\"tutorial-exercise\" data-label=\"filter\" data-completion=\"1\" data-diagnostics=\"1\" data-startover=\"1\" data-lines=\"0\" data-pipe=\"|&gt;\">\n\n```{.r .cell-code}\nmatch2023_df %>%\n  group_by(surface) %>%\n  summarise(\n    Mean_ace_Rate = mean(ace_rate, na.rm = TRUE),\n    Median_ace_Rate = median(ace_rate, na.rm = TRUE)\n  )\n```\n\n<script type=\"application/json\" data-ui-opts=\"1\">{\"engine\":\"r\",\"has_checker\":false,\"caption\":\"<span data-i18n=\\\"text.enginecap\\\" data-i18n-opts=\\\"{&quot;engine&quot;:&quot;R&quot;}\\\">R Code<\\/span>\"}</script></div>\n:::\n\n\n\n\n## Ace Rate vs. Surface Analysis\n\nTo more formally investigate the association between ace rate and surface, one might first think, \"We have a continuous variable (ace rate) and a three-level categorical variable (Surface: Grass, Hard, Clay), so we should use Analysis of Variance (ANOVA)!\"\n\nBut we will first show you to how to do the same thing using linear regression, and then demonstrate how this is identical to ANOVA.\n\n### Analyzing Association Using Linear Regression\n\nOften linear regression is first introduced using one continuous independent variable and a continuous outcome. Consider a simple model relating the number of aces to the number of service games in a match using a straight line:\n\n$$Aces=β0 + β1*ServiceGames$$\n\nThe blue line below illustrates the regression line from this equation:\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/plot1b-1.png){width=672}\n:::\n:::\n\n\n\n\nHere, β1 is the slope of the line: the average increase in the number of aces for a 1-unit increase in ServiceGames. In our data, that is approximately 0.6 more aces for each additional 1 service game.\n\nβ0 is the \"intercept\", or the average value of the outcome (aces) when the independent variables are zero (that is, for a match with ServiceGames = 0). This does not have a useful real-world interpretation, but it will be useful for our surface model below.\n\nSo, how can we include surface - a categorical independent variable - in the equation instead?\n\n#### Dummy Variable for Surface\n\nThe answer is to use **dummy variables**. These require transforming a categorical variable with K levels (for `surface`, this is 3) into K-1 (in our case, 2) variables that each take on the value 0 or 1.\n\nWe will create two new variables: `Hard` and `Clay`. We define `Hard` as 1 if the match is on hard court, and 0 otherwise. `Clay` is defined similarly. Thus we have:\n\nWhen the surface is Hard, `Hard` = 1, `Clay` = 0\n\nWhen the surface is Clay, `Hard` = 0, `Clay` = 1\n\nWhen the surface is Grass, `Hard` = 0, `Clay` = 0\n\nNotice although we did not include an explicit variable for `Grass`, we did not need to since grass surfaces are defined as the absence of a hard court or clay surface. This group - the one defined by all dummy variables being 0 - is called the **reference group**. Why this works will become apparent soon.\n\nHere is the code for creating these variables.\n\n\n\n\n::: {.cell exercise='true'}\n<div class=\"tutorial-exercise\" data-label=\"dummy\" data-completion=\"1\" data-diagnostics=\"1\" data-startover=\"1\" data-lines=\"0\" data-pipe=\"|&gt;\">\n\n```{.r .cell-code}\nmatch2023_df$Hard <- ifelse(match2023_df$surface == \"Hard\", 1, 0)\nmatch2023_df$Clay <- ifelse(match2023_df$surface == \"Clay\", 1, 0)\nhead(match2023_df)\n```\n\n<script type=\"application/json\" data-ui-opts=\"1\">{\"engine\":\"r\",\"has_checker\":false,\"caption\":\"<span data-i18n=\\\"text.enginecap\\\" data-i18n-opts=\\\"{&quot;engine&quot;:&quot;R&quot;}\\\">R Code<\\/span>\"}</script></div>\n:::\n\n::: {.cell exercise.setup='ace_rate_for_exer'}\n\n:::\n\n\n\n\n#### Interpreting Dummy Variables in Linear Regression\n\nWe can write these two variables, `Hard` and `Clay`, in a linear regression equation like so:\n\n$$AceRate=β0 + β1*Hard + β2*Clay$$\n\nRemember what we learned from the simple linear regression $$Aces=β0 + β1*ServiceGames$$\n\nβ1 represented the average change in aces for a 1-unit increase in ServiceGames (that is, the slope of a straight line through a scatterplot of the data). β0 represented the average aces when ServiceGames = 0.\n\nDummy variables work somewhat similarly.\n\n**Interpreting β0**\n\nβ0 should be the average of our dependent variable - ace rate - when all the independent variables are 0. Look back above at our variable definitions. What sort of Surface does `Hard` = 0 and `Clay` = 0 correspond to? Then, ask yourself...\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"panel panel-default tutorial-question-container\">\n<div data-label=\"equation_q_B0\" class=\"tutorial-question panel-body\">\n<div id=\"equation_q_B0-answer_container\" class=\"shiny-html-output\"></div>\n<div id=\"equation_q_B0-message_container\" class=\"shiny-html-output\"></div>\n<div id=\"equation_q_B0-action_button_container\" class=\"shiny-html-output\"></div>\n<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>\n</div>\n</div>\n```\n\n:::\n:::\n\n\n\n\nWe could write this mathematically (ignoring our error term) as $$AceRate(Grass)=β0 + β1*0 + β2*0 = β0$$\n\n**Interpreting β1**\n\nTo figure out how we interpret β1, let's start with a slightly different question: how can we get the average ace rate on a hard court surface? Let's look at our equation:\n\n$$AceRate=β0 + β1*Hard + β2*Clay$$\n\nFor a hard court surface, $$AceRate(Hard Court)=β0 + β1*1 + β2*0 $$ which simplifies to\n\n$$AceRate(Hard Court)=β0 + β1 $$\n\nThis helps us understand what β1 means: $$AceRate(Hard Court) - AceRate(Grass) = (β0 + β1) - (β0) = β1$$\n\nThus, β1 is the difference in average ace rate between grass and hard court. And that's what we're interested in!\n\nNote that using this equation, β1 \\> 0 means hard court has a higher ace rate, while β1 \\< 0 means hard court has a lower ace rate.\n\n**Interpreting β2**\n\nSee if you can apply this logic to interpret β2. HINT: Start by defining the average ace rate for a clay court match.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"panel panel-default tutorial-question-container\">\n<div data-label=\"equation_q_B2\" class=\"tutorial-question panel-body\">\n<div id=\"equation_q_B2-answer_container\" class=\"shiny-html-output\"></div>\n<div id=\"equation_q_B2-message_container\" class=\"shiny-html-output\"></div>\n<div id=\"equation_q_B2-action_button_container\" class=\"shiny-html-output\"></div>\n<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>\n</div>\n</div>\n```\n\n:::\n:::\n\n\n\n\n**Dummy Variables Show Differences Between Groups**\n\nIn fact, in general dummy variables can be interpreted as the average difference in our dependent variable between two groups: one defined by the group where the dummy variable is 1, and one defined by the reference group (where all dummy variables are 0).\n\nSo in our case: β1 = difference in ace rate between hard court and grass, and β2 = difference in ace rate between clay and grass\n\n#### Linear Regression Output\n\nLet's first look back at our table of mean ace rates for each surface type:\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  surface Mean_ace_Rate\n  <fct>           <dbl>\n1 Grass           0.582\n2 Hard            0.534\n3 Clay            0.332\n```\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"panel panel-default tutorial-question-container\">\n<div data-label=\"mean_diffs_q\" class=\"tutorial-question panel-body\">\n<div id=\"mean_diffs_q-answer_container\" class=\"shiny-html-output\"></div>\n<div id=\"mean_diffs_q-message_container\" class=\"shiny-html-output\"></div>\n<div id=\"mean_diffs_q-action_button_container\" class=\"shiny-html-output\"></div>\n<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>\n</div>\n</div>\n```\n\n:::\n:::\n\n\n\n\nNow compare that to the output from a linear regression of $$AceRate=β0 + β1*Hard + β2*Clay$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nace_surface_lm <- lm(ace_rate ~ surface, match2023_df)\nsummary(ace_surface_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = ace_rate ~ surface, data = match2023_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.58197 -0.16577 -0.01947  0.13296  1.17462 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.58197    0.01257   46.31  < 2e-16 ***\nsurfaceHard -0.04826    0.01441   -3.35 0.000823 ***\nsurfaceClay -0.24953    0.01476  -16.90  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.2262 on 2205 degrees of freedom\nMultiple R-squared:  0.1771,\tAdjusted R-squared:  0.1763 \nF-statistic: 237.2 on 2 and 2205 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nLook at the Coefficients table, the Estimate column. These are our estimates of β0, β1, and β2. Can you figure out which is which? Maybe the following questions will help:\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"panel panel-default tutorial-question-container\">\n<div data-label=\"output_B0\" class=\"tutorial-question panel-body\">\n<div id=\"output_B0-answer_container\" class=\"shiny-html-output\"></div>\n<div id=\"output_B0-message_container\" class=\"shiny-html-output\"></div>\n<div id=\"output_B0-action_button_container\" class=\"shiny-html-output\"></div>\n<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>\n</div>\n</div>\n```\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"panel panel-default tutorial-question-container\">\n<div data-label=\"output_B2\" class=\"tutorial-question panel-body\">\n<div id=\"output_B2-answer_container\" class=\"shiny-html-output\"></div>\n<div id=\"output_B2-message_container\" class=\"shiny-html-output\"></div>\n<div id=\"output_B2-action_button_container\" class=\"shiny-html-output\"></div>\n<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>\n</div>\n</div>\n```\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"panel panel-default tutorial-question-container\">\n<div data-label=\"output_B1\" class=\"tutorial-question panel-body\">\n<div id=\"output_B1-answer_container\" class=\"shiny-html-output\"></div>\n<div id=\"output_B1-message_container\" class=\"shiny-html-output\"></div>\n<div id=\"output_B1-action_button_container\" class=\"shiny-html-output\"></div>\n<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>\n</div>\n</div>\n```\n\n:::\n:::\n\n\n\n\n### Analyzing Association Using ANOVA\n\nLet's now compare these results to a \"traditional\" approach to comparing means across 3 or more groups: ANOVA. Here is the code to run an ANOVA of ace rates by surface types in R:\n\n\n\n\n::: {.cell exercise='true' exercise.setup='dummy_for_exer'}\n<div class=\"tutorial-exercise\" data-label=\"anova\" data-completion=\"1\" data-diagnostics=\"1\" data-startover=\"1\" data-lines=\"0\" data-pipe=\"|&gt;\">\n\n```{.r .cell-code}\nace_surface_anova <- aov(ace_rate ~ surface, match2023_df)\nanova(ace_surface_anova)\n```\n\n<script type=\"application/json\" data-ui-opts=\"1\">{\"engine\":\"r\",\"has_checker\":false,\"caption\":\"<span data-i18n=\\\"text.enginecap\\\" data-i18n-opts=\\\"{&quot;engine&quot;:&quot;R&quot;}\\\">R Code<\\/span>\"}</script></div>\n:::\n\n\n\n\nThe ANOVA table does not give us a lot of useful information. All it can tell us is whether the ace rates across the three surfaces are the same or different. This information is represented in the p-value for an F-test with F-statistic 237.2 and 2 and 2205 degrees of freedom. This p-value is under The `Pr(>F)` column: \\<2.2 x 10\\^-16. Because the p-value is \\<0.05, this indicates a statistically significant difference between surfaces at that threshold.\n\nWithout more work it cannot tell us which surfaces are different from which others or how different they are. The linear regression, on the other hand, gave us all of that!\n\nLet's do a little more work to also get p-values for pairwise comparisons between surfaces:\n\n\n\n\n::: {.cell exercise='true' exercise.setup='dummy_for_exer'}\n<div class=\"tutorial-exercise\" data-label=\"pairwise_anova\" data-completion=\"1\" data-diagnostics=\"1\" data-startover=\"1\" data-lines=\"0\" data-pipe=\"|&gt;\">\n\n```{.r .cell-code}\npairwise.t.test(match2023_df$ace_rate, match2023_df$surface, p.adj = \"none\")\n```\n\n<script type=\"application/json\" data-ui-opts=\"1\">{\"engine\":\"r\",\"has_checker\":false,\"caption\":\"<span data-i18n=\\\"text.enginecap\\\" data-i18n-opts=\\\"{&quot;engine&quot;:&quot;R&quot;}\\\">R Code<\\/span>\"}</script></div>\n:::\n\n\n\n\nThis shows statistically significant differences at the 0.05 threshold for hard court versus grass (p = 0.00082), clay versus grass (p \\< 2.2 x 10\\^-16), and clay versus hard court (p \\< 2.2 x 10\\^-16).\n\n### Comparing Outputs: ANOVA is a Linear Regression Model!\n\nLet's look again at our linear regression output:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nace_surface_lm <- lm(ace_rate ~ surface, match2023_df)\nsummary(ace_surface_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = ace_rate ~ surface, data = match2023_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.58197 -0.16577 -0.01947  0.13296  1.17462 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.58197    0.01257   46.31  < 2e-16 ***\nsurfaceHard -0.04826    0.01441   -3.35 0.000823 ***\nsurfaceClay -0.24953    0.01476  -16.90  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.2262 on 2205 degrees of freedom\nMultiple R-squared:  0.1771,\tAdjusted R-squared:  0.1763 \nF-statistic: 237.2 on 2 and 2205 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nLook at the last line of the output: an F-statistic of 237.2 on 2 and 2205 degrees of freedom, with a p-value of \\<2.2 x 10\\^-16. Exactly what we saw in our basic ANOVA!\n\nThen look under the Coefficients table at the `surfaceHard` and `surfaceClay` lines. These are our pairwise p-values comparing each of those groups to grass!\n\nThat is because **the ANOVA and linear regression are mathematically equivalent**.\n\nANOVA and linear regression are both linear models. They may seem different when considering conventional descriptions that emphasize ANOVA testing mean group differences across three or more groups and regression's emphasis on estimating coefficients relating two or more variables. But they are equivalent.\n\n## Conclusion\n\n### Tennis Aces by Surface\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"panel panel-default tutorial-question-container\">\n<div data-label=\"conclusion_sport\" class=\"tutorial-question panel-body\">\n<div id=\"conclusion_sport-answer_container\" class=\"shiny-html-output\"></div>\n<div id=\"conclusion_sport-message_container\" class=\"shiny-html-output\"></div>\n<div id=\"conclusion_sport-action_button_container\" class=\"shiny-html-output\"></div>\n<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>\n</div>\n</div>\n```\n\n:::\n:::\n\n\n\n\nA potential explanation for these differences is the impact of surface type on ball speed. Factors such as increased ball speed, unpredictable trajectories, or enhanced spinning torque can all contribute to a higher ace rate. Generally, the ball tends to travel at its fastest on grass surfaces, followed by hard court surfaces, and notably slower on clay surfaces. This is the same order we saw for ace rates. As the ball's speed decreases, the likelihood of a player serving the ball and the opponent failing to return it may be lower.\n\n### Statistical Lesson\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"panel panel-default tutorial-question-container\">\n<div data-label=\"conclusion_stats\" class=\"tutorial-question panel-body\">\n<div id=\"conclusion_stats-answer_container\" class=\"shiny-html-output\"></div>\n<div id=\"conclusion_stats-message_container\" class=\"shiny-html-output\"></div>\n<div id=\"conclusion_stats-action_button_container\" class=\"shiny-html-output\"></div>\n<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>\n</div>\n</div>\n```\n\n:::\n:::\n\n\n\n\nANOVA is mathematically equivalent to a simple linear regression model with dummy variables for one categorical independent variable. But the linear regression gives you more information with less work, and it is a much more flexible method capable of handling any number of continuous and categorical independent variables. Why would you use ANOVA when you could use linear regression instead?\n\nIn fact, many statistical tests you learn in Stats 101 - t-tests, ANOVA, Wilcoxon signed-rank test, Pearson and Spearman correlation coefficients, Mann-Whitney U test, Kruskal-Wallis test, Chi Square tests, and more - are all just special cases of linear regression. We could simply teach you linear regression to accomplish the goals of all these different methods.\n\nTo delve deeper into the link between common statistical tests and linear regression models, we recommend [this explanation from Jonas Lindeloev](https://lindeloev.github.io/tests-as-linear/linear_tests_cheat_sheet.pdf).\n\n## Extra Credit\n\nAs an optional extra credit assignment and to test your skills, try repeating the above analysis with `total_ServiceGames` as your dependent variable: a.) use linear regression and ANOVA to investigate the association between surface and the length of matches (defined as the number of service games), and b.) compare the outputs to demonstrate that they are equivalent but that the linear regression depicts more information about the association.\n\n### Authors\n\nZachary O. Binney, PhD MPH and Heyi Yang\n\nEmory University\n\npreserve2ba3e462002f10ac\npreserve81d607c0bdfdeb7e\npreserve1b7b358bcb9ff16d\npreserve270dbb191433218b\npreserve3157908748b8b657\npreserveebdc88855b0094de\npreserve9c1d460de0f5d568\npreserve32d4bafa52a0849a\npreserve9937f8900b16281d\npreserve0b32a47d19611bc3\npreserve004b6034a9365357\npreserved94e14aa28feb0df\npreservee880261d95bfcb9c\npreserve4c1e8e66843188e3\npreserve29c12e0020424b6b\npreservedf1b6629f3614250\npreservea60dd164550b139c\npreserve6e9fa9c2d6cef589\npreserve40e5e08eed949d26\npreservea0843bf44873cb1f\npreserve9524f19b90f47a1e\npreserve3bc19c3a71ffa363\npreserve888eb921614ba764\npreservea4105c124e7b93c9\npreserve387bf93859f19b49\npreserve60c8481f69015496\npreservedec69f3f293c6026\npreserve1ce2ff27e4f9ad22\npreserve5835ec57711b4f6b\npreserve31cbd482b97be7da\npreserve528f708a257384a9\npreserve83c4502521e36487\npreserve8a40e8327eebb2b6\npreserve921bb52e0ab1db57\npreserve4d8ef04eddcd4fcd\npreserved88461179afc1e3d\npreserve38b51252f7c241df\n\n<!--html_preserve-->\n<script type=\"application/shiny-prerendered\" data-context=\"dependencies\">\n{\"type\":\"list\",\"attributes\":{},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"jquery\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"3.6.0\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/3.6.0\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"jquery-3.6.0.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"jquerylib\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.1.4\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"font-awesome\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"6.4.2\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"fontawesome\"]}]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"css/all.min.css\",\"css/v4-shims.min.css\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"fontawesome\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.5.2\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"bootbox\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"5.5.2\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/bootbox\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"bootbox.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.11.5\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"idb-keyvalue\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"3.2.0\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/idb-keyval\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"idb-keyval-iife-compat.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.11.5\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tutorial\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.11.5\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/tutorial\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"tutorial.js\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"tutorial.css\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.11.5\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.10.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/ace\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.11.5\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboardjs\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.0.10\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/clipboardjs\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboard.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.11.5\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.10.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/ace\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.11.5\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboardjs\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.0.10\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/clipboardjs\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboard.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.11.5\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.10.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/ace\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.11.5\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboardjs\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.0.10\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/clipboardjs\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboard.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.11.5\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.10.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/ace\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.11.5\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboardjs\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.0.10\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/clipboardjs\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboard.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.11.5\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.10.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/ace\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.11.5\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboardjs\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.0.10\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/clipboardjs\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboard.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.11.5\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.10.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/ace\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.11.5\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboardjs\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.0.10\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/clipboardjs\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboard.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.11.5\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.10.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/ace\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.11.5\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboardjs\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.0.10\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/clipboardjs\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboard.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.11.5\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.10.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/ace\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.11.5\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboardjs\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.0.10\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/clipboardjs\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboard.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.11.5\"]}]}]}\n</script>\n<!--/html_preserve-->\n<!--html_preserve-->\n<script type=\"application/shiny-prerendered\" data-context=\"execution_dependencies\">\n{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"packages\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"packages\",\"version\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"data.frame\"]},\"row.names\":{\"type\":\"integer\",\"attributes\":{},\"value\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"backports\",\"base\",\"checkmate\",\"cli\",\"colorspace\",\"commonmark\",\"compiler\",\"datasets\",\"digest\",\"dplyr\",\"ellipsis\",\"evaluate\",\"fansi\",\"farver\",\"fastmap\",\"fontawesome\",\"forcats\",\"generics\",\"ggplot2\",\"glue\",\"graphics\",\"grDevices\",\"grid\",\"gridExtra\",\"gtable\",\"hms\",\"htmltools\",\"htmlwidgets\",\"httpuv\",\"jquerylib\",\"jsonlite\",\"knitr\",\"labeling\",\"later\",\"lattice\",\"learnr\",\"lifecycle\",\"lubridate\",\"magrittr\",\"markdown\",\"Matrix\",\"methods\",\"mgcv\",\"mime\",\"munsell\",\"nlme\",\"pacman\",\"pillar\",\"pkgconfig\",\"promises\",\"purrr\",\"R6\",\"Rcpp\",\"readr\",\"rlang\",\"rmarkdown\",\"rprojroot\",\"rstudioapi\",\"scales\",\"shiny\",\"splines\",\"stats\",\"stringi\",\"stringr\",\"tibble\",\"tidyr\",\"tidyselect\",\"tidyverse\",\"timechange\",\"tools\",\"tzdb\",\"utf8\",\"utils\",\"vctrs\",\"withr\",\"xfun\",\"xtable\",\"yaml\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.5.0\",\"4.4.1\",\"2.3.2\",\"3.6.3\",\"2.1-1\",\"1.9.2\",\"4.4.1\",\"4.4.1\",\"0.6.37\",\"1.1.4\",\"0.3.2\",\"0.24.0\",\"1.0.6\",\"2.1.2\",\"1.2.0\",\"0.5.2\",\"1.0.0\",\"0.1.3\",\"3.5.1\",\"1.7.0\",\"4.4.1\",\"4.4.1\",\"4.4.1\",\"2.3\",\"0.3.5\",\"1.1.3\",\"0.5.8.1\",\"1.6.4\",\"1.6.15\",\"0.1.4\",\"1.8.8\",\"1.48\",\"0.4.3\",\"1.4.1\",\"0.22-6\",\"0.11.5\",\"1.0.4\",\"1.9.3\",\"2.0.3\",\"1.13\",\"1.7-0\",\"4.4.1\",\"1.9-1\",\"0.12\",\"0.5.1\",\"3.1-164\",\"0.5.1\",\"1.9.0\",\"2.0.3\",\"1.3.2\",\"1.0.2\",\"2.5.1\",\"1.0.13\",\"2.1.5\",\"1.1.4\",\"2.28\",\"2.0.4\",\"0.16.0\",\"1.3.0\",\"1.10.0\",\"4.4.1\",\"4.4.1\",\"1.8.4\",\"1.5.1\",\"3.2.1\",\"1.3.1\",\"1.2.1\",\"2.0.0\",\"0.3.0\",\"4.4.1\",\"0.4.0\",\"1.2.4\",\"4.4.1\",\"0.6.5\",\"3.0.1\",\"0.49\",\"1.8-4\",\"2.3.10\"]}]}]}\n</script>\n<!--/html_preserve-->",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {
      "preserve004b6034a9365357": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::question_prerendered_chunk(structure(list(type = \"learnr_radio\", label = \"logicals2\", question = structure(\"What does <code>surface<\\u002fcode> represent?\", html = TRUE, class = c(\"html\", \n\"character\")), answers = list(structure(list(id = \"lnr_ans_fb83e5b\", \n    option = \"The number of aces in the match\", value = \"The number of aces in the match\", \n    label = structure(\"The number of aces in the match\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_fc9c597\", \n    option = \"The number of service games in the match\", value = \"The number of service games in the match\", \n    label = structure(\"The number of service games in the match\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_6e69091\", \n    option = \"Whether the game was played on clay, grass, or hard court\", \n    value = \"Whether the game was played on clay, grass, or hard court\", \n    label = structure(\"Whether the game was played on clay, grass, or hard court\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = TRUE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_e3361b2\", \n    option = \"The type of surface the winner prefers\", value = \"The type of surface the winner prefers\", \n    label = structure(\"The type of surface the winner prefers\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\"))), button_labels = list(submit = structure(\"<span data-i18n=\\\"button.questionsubmit\\\">Submit Answer<\\u002fspan>\", html = TRUE, class = c(\"html\", \n\"character\")), try_again = structure(\"<span data-i18n=\\\"button.questiontryagain\\\">Try Again<\\u002fspan>\", html = TRUE, class = c(\"html\", \n\"character\"))), messages = list(correct = structure(\"Correct!\", html = TRUE, class = c(\"html\", \n\"character\")), try_again = structure(\"Incorrect\", html = TRUE, class = c(\"html\", \n\"character\")), incorrect = structure(\"Incorrect\", html = TRUE, class = c(\"html\", \n\"character\")), message = NULL, post_message = NULL), ids = list(\n    answer = \"logicals2-answer\", question = \"logicals2\"), loading = NULL, \n    random_answer_order = FALSE, allow_retry = TRUE, seed = 9636720.99551255, \n    options = list()), class = c(\"learnr_radio\", \"tutorial_question\"\n)), session = session)\n</script>\n",
      "preserve0b32a47d19611bc3": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::question_prerendered_chunk(structure(list(type = \"learnr_radio\", label = \"logicals1\", question = structure(\"What does <code>winner<\\u002fcode> represent?\", html = TRUE, class = c(\"html\", \n\"character\")), answers = list(structure(list(id = \"lnr_ans_41a78d6\", \n    option = \"The name of the player who won the match\", value = \"The name of the player who won the match\", \n    label = structure(\"The name of the player who won the match\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = TRUE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_5b6d7d6\", \n    option = \"The tournament the match was part of\", value = \"The tournament the match was part of\", \n    label = structure(\"The tournament the match was part of\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_d4b13e5\", \n    option = \"The name of the player who lost the match\", value = \"The name of the player who lost the match\", \n    label = structure(\"The name of the player who lost the match\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_eaa3777\", \n    option = \"The round of the match\", value = \"The round of the match\", \n    label = structure(\"The round of the match\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\"))), button_labels = list(submit = structure(\"<span data-i18n=\\\"button.questionsubmit\\\">Submit Answer<\\u002fspan>\", html = TRUE, class = c(\"html\", \n\"character\")), try_again = structure(\"<span data-i18n=\\\"button.questiontryagain\\\">Try Again<\\u002fspan>\", html = TRUE, class = c(\"html\", \n\"character\"))), messages = list(correct = structure(\"Correct!\", html = TRUE, class = c(\"html\", \n\"character\")), try_again = structure(\"Incorrect\", html = TRUE, class = c(\"html\", \n\"character\")), incorrect = structure(\"Incorrect\", html = TRUE, class = c(\"html\", \n\"character\")), message = NULL, post_message = NULL), ids = list(\n    answer = \"logicals1-answer\", question = \"logicals1\"), loading = NULL, \n    random_answer_order = FALSE, allow_retry = TRUE, seed = 2016912104.0608, \n    options = list()), class = c(\"learnr_radio\", \"tutorial_question\"\n)), session = session)\n</script>\n",
      "preserve1b7b358bcb9ff16d": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::prepare_tutorial_state(session)\n</script>\n",
      "preserve1ce2ff27e4f9ad22": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::question_prerendered_chunk(structure(list(type = \"learnr_radio\", label = \"output_B0\", question = structure(\"Which row of the Coefficients table in the output above corresponds to the average ace rate for grass surfaces?\", html = TRUE, class = c(\"html\", \n\"character\")), answers = list(structure(list(id = \"lnr_ans_25c6c39\", \n    option = \"(Intercept) = 0.582\", value = \"(Intercept) = 0.582\", \n    label = structure(\"(Intercept) = 0.582\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = TRUE, message = structure(\"This is the mean ace rate for grass surfaces, so this must be β0!\", html = TRUE, class = c(\"html\", \n    \"character\")), type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_35d76a6\", \n    option = \"surfaceHard = -0.048\", value = \"surfaceHard = -0.048\", \n    label = structure(\"surfaceHard = -0.048\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_23093f3\", \n    option = \"surfaceClay = -0.250\", value = \"surfaceClay = -0.250\", \n    label = structure(\"surfaceClay = -0.250\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\"))), button_labels = list(submit = structure(\"<span data-i18n=\\\"button.questionsubmit\\\">Submit Answer<\\u002fspan>\", html = TRUE, class = c(\"html\", \n\"character\")), try_again = structure(\"<span data-i18n=\\\"button.questiontryagain\\\">Try Again<\\u002fspan>\", html = TRUE, class = c(\"html\", \n\"character\"))), messages = list(correct = structure(\"Correct!\", html = TRUE, class = c(\"html\", \n\"character\")), try_again = structure(\"Incorrect\", html = TRUE, class = c(\"html\", \n\"character\")), incorrect = structure(\"Incorrect\", html = TRUE, class = c(\"html\", \n\"character\")), message = NULL, post_message = NULL), ids = list(\n    answer = \"output_B0-answer\", question = \"output_B0\"), loading = NULL, \n    random_answer_order = FALSE, allow_retry = TRUE, seed = 1289602780.39948, \n    options = list()), class = c(\"learnr_radio\", \"tutorial_question\"\n)), session = session)\n</script>\n",
      "preserve270dbb191433218b": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::i18n_observe_tutorial_language(input, session)\n</script>\n",
      "preserve29c12e0020424b6b": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::store_exercise_cache(structure(list(label = \"plot1\", global_setup = structure(c(\"\", \n\"pacman::p_load(learnr, tidyverse, stats, knitr, gridExtra)\", \n\"  \", \"# match2023 <- read.csv(\\\"atp_matches_2023.csv\\\")\", \"#   \", \n\"# match2023_df <- match2023 %>%\", \"#     select(tourney_name, round, winner_name, loser_name, surface,w_ace,l_ace,w_SvGms,l_SvGms) %>%\", \n\"#     na.omit(match2023_df) %>% \", \"#     mutate(total_ServiceGames = w_SvGms + l_SvGms) %>%\", \n\"#     mutate(total_aces = (l_ace + w_ace),\", \"#            surface = factor(surface, levels = c(\\\"Grass\\\", \\\"Hard\\\", \\\"Clay\\\"))) %>% \", \n\"#   select(-w_ace, -l_ace, -w_SvGms, -l_SvGms) %>% \", \"#   filter(tourney_name != \\\"United Cup\\\") %>%  # Exclude United Cup, which is a country team tournament\", \n\"#   as_tibble()\", \"\", \"#write.csv(match2023_df, \\\"atp_matches_2023_analysis.csv\\\")\", \n\"\", \"match2023_df <- read.csv(\\\"atp_matches_2023_analysis.csv\\\") %>% \", \n\"  mutate(surface = factor(surface, levels = c(\\\"Grass\\\",\\\"Hard\\\", \\\"Clay\\\")))\", \n\"\", \"\", \"\"), chunk_opts = list(label = \"setup\", include = FALSE)), \n    setup = NULL, chunks = list(list(label = \"plot1\", code = \"\\nggplot(match2023_df, aes(x = total_ServiceGames, y = total_aces)) +\\n  geom_point() +\\n  geom_smooth(method = \\\"lm\\\", se = FALSE, color = \\\"blue\\\") +\\n  labs(x = \\\"Service Games in Match\\\", y = \\\"Aces in Match\\\") +\\n  ggtitle(\\\"Association Between Number of Aces and Service Games in Tennis Matches\\\")\\n\", \n        opts = list(label = \"\\\"plot1\\\"\", exercise = \"TRUE\"), \n        engine = \"r\")), code_check = NULL, error_check = NULL, \n    check = NULL, solution = NULL, tests = NULL, options = list(\n        eval = FALSE, echo = TRUE, results = \"markup\", tidy = FALSE, \n        tidy.opts = NULL, collapse = FALSE, prompt = FALSE, comment = NA, \n        highlight = FALSE, size = \"normalsize\", background = \"#F7F7F7\", \n        strip.white = TRUE, cache = 0, cache.path = \"index_cache/html/\", \n        cache.vars = NULL, cache.lazy = TRUE, dependson = NULL, \n        autodep = FALSE, cache.rebuild = FALSE, fig.keep = \"high\", \n        fig.show = \"asis\", fig.align = \"default\", fig.path = \"index_files/figure-html/\", \n        dev = \"png\", dev.args = NULL, dpi = 192, fig.ext = \"png\", \n        fig.width = 7L, fig.height = 5L, fig.env = \"figure\", \n        fig.cap = NULL, fig.scap = NULL, fig.lp = \"fig:\", fig.subcap = NULL, \n        fig.pos = \"\", out.width = 672L, out.height = NULL, out.extra = NULL, \n        fig.retina = 2, external = TRUE, sanitize = FALSE, interval = 1, \n        aniopts = \"controls,loop\", warning = TRUE, error = FALSE, \n        message = TRUE, render = NULL, ref.label = NULL, child = NULL, \n        engine = \"r\", split = FALSE, include = TRUE, purl = TRUE, \n        fig.asp = NULL, fenced.echo = FALSE, ft.shadow = FALSE, \n        label = \"plot1\", exercise = TRUE, original.params.src = \"r plot1, exercise = TRUE\", \n        chunk.echo = FALSE, code = c(\"\", \"ggplot(match2023_df, aes(x = total_ServiceGames, y = total_aces)) +\", \n        \"  geom_point() +\", \"  geom_smooth(method = \\\"lm\\\", se = FALSE, color = \\\"blue\\\") +\", \n        \"  labs(x = \\\"Service Games in Match\\\", y = \\\"Aces in Match\\\") +\", \n        \"  ggtitle(\\\"Association Between Number of Aces and Service Games in Tennis Matches\\\")\", \n        \"\"), out.width.px = 672L, out.height.px = 480L, params.src = \"r plot1, exercise = TRUE\", \n        fig.num = 0, exercise.df_print = \"default\", exercise.checker = \"NULL\"), \n    engine = \"r\", version = \"4\"), class = c(\"r\", \"tutorial_exercise\"\n)))\n</script>\n",
      "preserve2ba3e462002f10ac": "\n<script type=\"application/shiny-prerendered\" data-context=\"server-start\">\n\npacman::p_load(learnr, tidyverse, stats, knitr, gridExtra)\n  \n# match2023 <- read.csv(\"atp_matches_2023.csv\")\n#   \n# match2023_df <- match2023 %>%\n#     select(tourney_name, round, winner_name, loser_name, surface,w_ace,l_ace,w_SvGms,l_SvGms) %>%\n#     na.omit(match2023_df) %>% \n#     mutate(total_ServiceGames = w_SvGms + l_SvGms) %>%\n#     mutate(total_aces = (l_ace + w_ace),\n#            surface = factor(surface, levels = c(\"Grass\", \"Hard\", \"Clay\"))) %>% \n#   select(-w_ace, -l_ace, -w_SvGms, -l_SvGms) %>% \n#   filter(tourney_name != \"United Cup\") %>%  # Exclude United Cup, which is a country team tournament\n#   as_tibble()\n\n#write.csv(match2023_df, \"atp_matches_2023_analysis.csv\")\n\nmatch2023_df <- read.csv(\"atp_matches_2023_analysis.csv\") %>% \n  mutate(surface = factor(surface, levels = c(\"Grass\",\"Hard\", \"Clay\")))\n\n\n\n</script>\n",
      "preserve3157908748b8b657": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nsession$onSessionEnded(function() {\n        learnr:::event_trigger(session, \"session_stop\")\n      })\n</script>\n",
      "preserve31cbd482b97be7da": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::question_prerendered_chunk(structure(list(type = \"learnr_radio\", label = \"output_B1\", question = structure(\"Which row of the Coefficients table in the output above corresponds to the average ace rate difference for hard court versus grass surfaces?\", html = TRUE, class = c(\"html\", \n\"character\")), answers = list(structure(list(id = \"lnr_ans_52788d\", \n    option = \"(Intercept) = 0.582\", value = \"(Intercept) = 0.582\", \n    label = structure(\"(Intercept) = 0.582\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_cc9b62f\", \n    option = \"surfaceHard = -0.048\", value = \"surfaceHard = -0.048\", \n    label = structure(\"surfaceHard = -0.048\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = TRUE, message = structure(\"This is the mean ace rate difference for hard court versus grass surfaces, so this must be β1!\", html = TRUE, class = c(\"html\", \n    \"character\")), type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_52bb575\", \n    option = \"surfaceClay = -0.250\", value = \"surfaceClay = -0.250\", \n    label = structure(\"surfaceClay = -0.250\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\"))), button_labels = list(submit = structure(\"<span data-i18n=\\\"button.questionsubmit\\\">Submit Answer<\\u002fspan>\", html = TRUE, class = c(\"html\", \n\"character\")), try_again = structure(\"<span data-i18n=\\\"button.questiontryagain\\\">Try Again<\\u002fspan>\", html = TRUE, class = c(\"html\", \n\"character\"))), messages = list(correct = structure(\"Correct!\", html = TRUE, class = c(\"html\", \n\"character\")), try_again = structure(\"Incorrect\", html = TRUE, class = c(\"html\", \n\"character\")), incorrect = structure(\"Incorrect\", html = TRUE, class = c(\"html\", \n\"character\")), message = NULL, post_message = NULL), ids = list(\n    answer = \"output_B1-answer\", question = \"output_B1\"), loading = NULL, \n    random_answer_order = FALSE, allow_retry = TRUE, seed = 765476815.643547, \n    options = list()), class = c(\"learnr_radio\", \"tutorial_question\"\n)), session = session)\n</script>\n",
      "preserve32d4bafa52a0849a": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::store_exercise_cache(structure(list(label = \"head\", global_setup = structure(c(\"\", \n\"pacman::p_load(learnr, tidyverse, stats, knitr, gridExtra)\", \n\"  \", \"# match2023 <- read.csv(\\\"atp_matches_2023.csv\\\")\", \"#   \", \n\"# match2023_df <- match2023 %>%\", \"#     select(tourney_name, round, winner_name, loser_name, surface,w_ace,l_ace,w_SvGms,l_SvGms) %>%\", \n\"#     na.omit(match2023_df) %>% \", \"#     mutate(total_ServiceGames = w_SvGms + l_SvGms) %>%\", \n\"#     mutate(total_aces = (l_ace + w_ace),\", \"#            surface = factor(surface, levels = c(\\\"Grass\\\", \\\"Hard\\\", \\\"Clay\\\"))) %>% \", \n\"#   select(-w_ace, -l_ace, -w_SvGms, -l_SvGms) %>% \", \"#   filter(tourney_name != \\\"United Cup\\\") %>%  # Exclude United Cup, which is a country team tournament\", \n\"#   as_tibble()\", \"\", \"#write.csv(match2023_df, \\\"atp_matches_2023_analysis.csv\\\")\", \n\"\", \"match2023_df <- read.csv(\\\"atp_matches_2023_analysis.csv\\\") %>% \", \n\"  mutate(surface = factor(surface, levels = c(\\\"Grass\\\",\\\"Hard\\\", \\\"Clay\\\")))\", \n\"\", \"\", \"\"), chunk_opts = list(label = \"setup\", include = FALSE)), \n    setup = NULL, chunks = list(list(label = \"head\", code = \"# Print the (first 1000 rows of) the data\\nmatch2023_df\\n\\n# Get a summary of the data\\nsummary(match2023_df)\\n\", \n        opts = list(label = \"\\\"head\\\"\", exercise = \"TRUE\", exercise.eval = \"FALSE\"), \n        engine = \"r\")), code_check = NULL, error_check = NULL, \n    check = NULL, solution = NULL, tests = NULL, options = list(\n        eval = FALSE, echo = TRUE, results = \"markup\", tidy = FALSE, \n        tidy.opts = NULL, collapse = FALSE, prompt = FALSE, comment = NA, \n        highlight = FALSE, size = \"normalsize\", background = \"#F7F7F7\", \n        strip.white = TRUE, cache = 0, cache.path = \"index_cache/html/\", \n        cache.vars = NULL, cache.lazy = TRUE, dependson = NULL, \n        autodep = FALSE, cache.rebuild = FALSE, fig.keep = \"high\", \n        fig.show = \"asis\", fig.align = \"default\", fig.path = \"index_files/figure-html/\", \n        dev = \"png\", dev.args = NULL, dpi = 192, fig.ext = \"png\", \n        fig.width = 7L, fig.height = 5L, fig.env = \"figure\", \n        fig.cap = NULL, fig.scap = NULL, fig.lp = \"fig:\", fig.subcap = NULL, \n        fig.pos = \"\", out.width = 672L, out.height = NULL, out.extra = NULL, \n        fig.retina = 2, external = TRUE, sanitize = FALSE, interval = 1, \n        aniopts = \"controls,loop\", warning = TRUE, error = FALSE, \n        message = TRUE, render = NULL, ref.label = NULL, child = NULL, \n        engine = \"r\", split = FALSE, include = TRUE, purl = TRUE, \n        fig.asp = NULL, fenced.echo = FALSE, ft.shadow = FALSE, \n        label = \"head\", exercise = TRUE, exercise.eval = FALSE, \n        original.params.src = \"r head, exercise = TRUE, exercise.eval = FALSE\", \n        chunk.echo = FALSE, code = c(\"# Print the (first 1000 rows of) the data\", \n        \"match2023_df\", \"\", \"# Get a summary of the data\", \"summary(match2023_df)\", \n        \"\"), out.width.px = 672L, out.height.px = 480L, params.src = \"r head, exercise = TRUE, exercise.eval = FALSE\", \n        fig.num = 0, exercise.df_print = \"default\", exercise.checker = \"NULL\"), \n    engine = \"r\", version = \"4\"), class = c(\"r\", \"tutorial_exercise\"\n)))\n</script>\n",
      "preserve387bf93859f19b49": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::question_prerendered_chunk(structure(list(type = \"learnr_text\", label = \"equation_q_B0\", \n    question = structure(\"What does β0 in our model AceRate=β0 + β1<em>Hard + β2<\\u002fem>Clay + ε represent? β0 is the average _______ when __________. (The blanks can be more than one word.)\", html = TRUE, class = c(\"html\", \n    \"character\")), answers = list(structure(list(id = \"lnr_ans_e175443\", \n        option = \"\", value = \"\", label = structure(\"\", html = TRUE, class = c(\"html\", \n        \"character\")), correct = TRUE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n    \"tutorial_quiz_answer\"))), button_labels = list(submit = structure(\"<span data-i18n=\\\"button.questionsubmit\\\">Submit Answer<\\u002fspan>\", html = TRUE, class = c(\"html\", \n    \"character\")), try_again = structure(\"<span data-i18n=\\\"button.questiontryagain\\\">Try Again<\\u002fspan>\", html = TRUE, class = c(\"html\", \n    \"character\"))), messages = list(correct = NULL, try_again = NULL, \n        incorrect = NULL, message = structure(\"Example correct answer: β0 is the average <u>ace rate<\\u002fu> when <u>playing on grass<\\u002fu>, or AceRate(Grass).\", html = TRUE, class = c(\"html\", \n        \"character\")), post_message = NULL), ids = list(answer = \"equation_q_B0-answer\", \n        question = \"equation_q_B0\"), loading = NULL, random_answer_order = FALSE, \n    allow_retry = FALSE, seed = 308319909.356427, options = list(\n        placeholder = \"Enter answer here...\", trim = TRUE, rows = 5)), class = c(\"learnr_text\", \n\"tutorial_question\")), session = session)\n</script>\n",
      "preserve38b51252f7c241df": "\n<script type=\"application/shiny-prerendered\" data-context=\"server-extras\">\nojs_define <- function(..., .session = shiny::getDefaultReactiveDomain()) {\n  quos <- rlang::enquos(...)\n  vars <- rlang::list2(...)\n  nm <- names(vars)\n  if (is.null(nm)) {\n    nm <- rep_len(\"\", length(vars))\n  }\n  mapply(function(q, nm, val) {\n    # Infer name, if possible\n    if (nm == \"\") {\n      tryCatch({\n        nm <- rlang::as_name(q)\n      }, error = function(e) {\n        code <- paste(collapse = \"\\n\", deparse(rlang::f_rhs(q)))\n        stop(\"ojs_define() could not create a name for the argument: \", code)\n      })\n    }\n    .session$output[[nm]] <- val\n    outputOptions(.session$output, nm, suspendWhenHidden = FALSE)\n    .session$sendCustomMessage(\"ojs-export\", list(name = nm))\n    NULL\n  }, quos, nm, vars, SIMPLIFY = FALSE, USE.NAMES = FALSE)\n  invisible()\n}\n</script>\n",
      "preserve3bc19c3a71ffa363": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::store_exercise_cache(structure(list(label = \"filter\", global_setup = structure(c(\"\", \n\"pacman::p_load(learnr, tidyverse, stats, knitr, gridExtra)\", \n\"  \", \"# match2023 <- read.csv(\\\"atp_matches_2023.csv\\\")\", \"#   \", \n\"# match2023_df <- match2023 %>%\", \"#     select(tourney_name, round, winner_name, loser_name, surface,w_ace,l_ace,w_SvGms,l_SvGms) %>%\", \n\"#     na.omit(match2023_df) %>% \", \"#     mutate(total_ServiceGames = w_SvGms + l_SvGms) %>%\", \n\"#     mutate(total_aces = (l_ace + w_ace),\", \"#            surface = factor(surface, levels = c(\\\"Grass\\\", \\\"Hard\\\", \\\"Clay\\\"))) %>% \", \n\"#   select(-w_ace, -l_ace, -w_SvGms, -l_SvGms) %>% \", \"#   filter(tourney_name != \\\"United Cup\\\") %>%  # Exclude United Cup, which is a country team tournament\", \n\"#   as_tibble()\", \"\", \"#write.csv(match2023_df, \\\"atp_matches_2023_analysis.csv\\\")\", \n\"\", \"match2023_df <- read.csv(\\\"atp_matches_2023_analysis.csv\\\") %>% \", \n\"  mutate(surface = factor(surface, levels = c(\\\"Grass\\\",\\\"Hard\\\", \\\"Clay\\\")))\", \n\"\", \"\", \"\"), chunk_opts = list(label = \"setup\", include = FALSE)), \n    setup = \" match2023_df <- match2023_df %>%\\n    mutate(ace_rate = total_aces/total_ServiceGames)\", \n    chunks = list(list(label = \"ace_rate_for_exer\", code = \" match2023_df <- match2023_df %>%\\n    mutate(ace_rate = total_aces/total_ServiceGames)\", \n        opts = list(label = \"\\\"ace_rate_for_exer\\\"\", include = \"FALSE\"), \n        engine = \"r\"), list(label = \"filter\", code = \"match2023_df %>%\\n  group_by(surface) %>%\\n  summarise(\\n    Mean_ace_Rate = mean(ace_rate, na.rm = TRUE),\\n    Median_ace_Rate = median(ace_rate, na.rm = TRUE)\\n  )\", \n        opts = list(label = \"\\\"filter\\\"\", exercise = \"TRUE\", \n            exercise.setup = \"\\\"ace_rate_for_exer\\\"\"), engine = \"r\")), \n    code_check = NULL, error_check = NULL, check = NULL, solution = NULL, \n    tests = NULL, options = list(eval = FALSE, echo = TRUE, results = \"markup\", \n        tidy = FALSE, tidy.opts = NULL, collapse = FALSE, prompt = FALSE, \n        comment = NA, highlight = FALSE, size = \"normalsize\", \n        background = \"#F7F7F7\", strip.white = TRUE, cache = 0, \n        cache.path = \"index_cache/html/\", cache.vars = NULL, \n        cache.lazy = TRUE, dependson = NULL, autodep = FALSE, \n        cache.rebuild = FALSE, fig.keep = \"high\", fig.show = \"asis\", \n        fig.align = \"default\", fig.path = \"index_files/figure-html/\", \n        dev = \"png\", dev.args = NULL, dpi = 192, fig.ext = \"png\", \n        fig.width = 7L, fig.height = 5L, fig.env = \"figure\", \n        fig.cap = NULL, fig.scap = NULL, fig.lp = \"fig:\", fig.subcap = NULL, \n        fig.pos = \"\", out.width = 672L, out.height = NULL, out.extra = NULL, \n        fig.retina = 2, external = TRUE, sanitize = FALSE, interval = 1, \n        aniopts = \"controls,loop\", warning = TRUE, error = FALSE, \n        message = TRUE, render = NULL, ref.label = NULL, child = NULL, \n        engine = \"r\", split = FALSE, include = TRUE, purl = TRUE, \n        fig.asp = NULL, fenced.echo = FALSE, ft.shadow = FALSE, \n        label = \"filter\", exercise = TRUE, exercise.setup = \"ace_rate_for_exer\", \n        original.params.src = \"r filter, exercise=TRUE, exercise.setup = \\\"ace_rate_for_exer\\\"\", \n        chunk.echo = FALSE, code = c(\"match2023_df %>%\", \"  group_by(surface) %>%\", \n        \"  summarise(\", \"    Mean_ace_Rate = mean(ace_rate, na.rm = TRUE),\", \n        \"    Median_ace_Rate = median(ace_rate, na.rm = TRUE)\", \n        \"  )\"), out.width.px = 672L, out.height.px = 480L, params.src = \"r filter, exercise=TRUE, exercise.setup = \\\"ace_rate_for_exer\\\"\", \n        fig.num = 0, exercise.df_print = \"default\", exercise.checker = \"NULL\"), \n    engine = \"r\", version = \"4\"), class = c(\"r\", \"tutorial_exercise\"\n)))\n</script>\n",
      "preserve40e5e08eed949d26": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::store_exercise_cache(structure(list(label = \"mean_and_boxplots\", global_setup = structure(c(\"\", \n\"pacman::p_load(learnr, tidyverse, stats, knitr, gridExtra)\", \n\"  \", \"# match2023 <- read.csv(\\\"atp_matches_2023.csv\\\")\", \"#   \", \n\"# match2023_df <- match2023 %>%\", \"#     select(tourney_name, round, winner_name, loser_name, surface,w_ace,l_ace,w_SvGms,l_SvGms) %>%\", \n\"#     na.omit(match2023_df) %>% \", \"#     mutate(total_ServiceGames = w_SvGms + l_SvGms) %>%\", \n\"#     mutate(total_aces = (l_ace + w_ace),\", \"#            surface = factor(surface, levels = c(\\\"Grass\\\", \\\"Hard\\\", \\\"Clay\\\"))) %>% \", \n\"#   select(-w_ace, -l_ace, -w_SvGms, -l_SvGms) %>% \", \"#   filter(tourney_name != \\\"United Cup\\\") %>%  # Exclude United Cup, which is a country team tournament\", \n\"#   as_tibble()\", \"\", \"#write.csv(match2023_df, \\\"atp_matches_2023_analysis.csv\\\")\", \n\"\", \"match2023_df <- read.csv(\\\"atp_matches_2023_analysis.csv\\\") %>% \", \n\"  mutate(surface = factor(surface, levels = c(\\\"Grass\\\",\\\"Hard\\\", \\\"Clay\\\")))\", \n\"\", \"\", \"\"), chunk_opts = list(label = \"setup\", include = FALSE)), \n    setup = \" match2023_df <- match2023_df %>%\\n    mutate(ace_rate = total_aces/total_ServiceGames)\", \n    chunks = list(list(label = \"ace_rate_for_exer\", code = \" match2023_df <- match2023_df %>%\\n    mutate(ace_rate = total_aces/total_ServiceGames)\", \n        opts = list(label = \"\\\"ace_rate_for_exer\\\"\", include = \"FALSE\"), \n        engine = \"r\"), list(label = \"mean_and_boxplots\", code = \"# Get average overall ace rate\\nmean_acerate <- mean(match2023_df$ace_rate, na.rm = TRUE)\\n\\n# Create boxplots with overall mean ace rate as red line\\nggplot(match2023_df, aes(x = surface, y = ace_rate)) +\\n  geom_boxplot() +\\n  labs(title = \\\"Ace Rate by Surface Type\\\",\\n       x = \\\"Surface Type\\\",\\n       y = \\\"Ace Rate\\\",\\n       caption = \\\"Red line is overall mean ace rate across all surfaces.\\\") +\\n  geom_hline(yintercept = mean_acerate, linetype = \\\"dashed\\\", color = \\\"red\\\")+\\n  theme_minimal()+\\n  scale_y_continuous(limits = c(0, 0.75), breaks = seq(0, 0.75, by = 0.25))\\n\", \n        opts = list(label = \"\\\"mean_and_boxplots\\\"\", exercise = \"TRUE\", \n            exercise.setup = \"\\\"ace_rate_for_exer\\\"\"), engine = \"r\")), \n    code_check = NULL, error_check = NULL, check = NULL, solution = NULL, \n    tests = NULL, options = list(eval = FALSE, echo = TRUE, results = \"markup\", \n        tidy = FALSE, tidy.opts = NULL, collapse = FALSE, prompt = FALSE, \n        comment = NA, highlight = FALSE, size = \"normalsize\", \n        background = \"#F7F7F7\", strip.white = TRUE, cache = 0, \n        cache.path = \"index_cache/html/\", cache.vars = NULL, \n        cache.lazy = TRUE, dependson = NULL, autodep = FALSE, \n        cache.rebuild = FALSE, fig.keep = \"high\", fig.show = \"asis\", \n        fig.align = \"default\", fig.path = \"index_files/figure-html/\", \n        dev = \"png\", dev.args = NULL, dpi = 192, fig.ext = \"png\", \n        fig.width = 7L, fig.height = 5L, fig.env = \"figure\", \n        fig.cap = NULL, fig.scap = NULL, fig.lp = \"fig:\", fig.subcap = NULL, \n        fig.pos = \"\", out.width = 672L, out.height = NULL, out.extra = NULL, \n        fig.retina = 2, external = TRUE, sanitize = FALSE, interval = 1, \n        aniopts = \"controls,loop\", warning = TRUE, error = FALSE, \n        message = TRUE, render = NULL, ref.label = NULL, child = NULL, \n        engine = \"r\", split = FALSE, include = TRUE, purl = TRUE, \n        fig.asp = NULL, fenced.echo = FALSE, ft.shadow = FALSE, \n        label = \"mean_and_boxplots\", exercise = TRUE, exercise.setup = \"ace_rate_for_exer\", \n        original.params.src = \"r mean_and_boxplots, exercise = TRUE, exercise.setup = \\\"ace_rate_for_exer\\\"\", \n        chunk.echo = FALSE, code = c(\"# Get average overall ace rate\", \n        \"mean_acerate <- mean(match2023_df$ace_rate, na.rm = TRUE)\", \n        \"\", \"# Create boxplots with overall mean ace rate as red line\", \n        \"ggplot(match2023_df, aes(x = surface, y = ace_rate)) +\", \n        \"  geom_boxplot() +\", \"  labs(title = \\\"Ace Rate by Surface Type\\\",\", \n        \"       x = \\\"Surface Type\\\",\", \"       y = \\\"Ace Rate\\\",\", \n        \"       caption = \\\"Red line is overall mean ace rate across all surfaces.\\\") +\", \n        \"  geom_hline(yintercept = mean_acerate, linetype = \\\"dashed\\\", color = \\\"red\\\")+\", \n        \"  theme_minimal()+\", \"  scale_y_continuous(limits = c(0, 0.75), breaks = seq(0, 0.75, by = 0.25))\", \n        \"\"), out.width.px = 672L, out.height.px = 480L, params.src = \"r mean_and_boxplots, exercise = TRUE, exercise.setup = \\\"ace_rate_for_exer\\\"\", \n        fig.num = 0, exercise.df_print = \"default\", exercise.checker = \"NULL\"), \n    engine = \"r\", version = \"4\"), class = c(\"r\", \"tutorial_exercise\"\n)))\n</script>\n",
      "preserve4c1e8e66843188e3": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\n`tutorial-exercise-plot1-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-plot1-code-editor`)), session)\noutput$`tutorial-exercise-plot1-output` <- renderUI({\n  `tutorial-exercise-plot1-result`()\n})\n</script>\n",
      "preserve4d8ef04eddcd4fcd": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::question_prerendered_chunk(structure(list(type = \"learnr_text\", label = \"conclusion_sport\", \n    question = structure(\"In the end, we can conclude that:\", html = TRUE, class = c(\"html\", \n    \"character\")), answers = list(structure(list(id = \"lnr_ans_aeb7e63\", \n        option = \"\", value = \"\", label = structure(\"\", html = TRUE, class = c(\"html\", \n        \"character\")), correct = TRUE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n    \"tutorial_quiz_answer\"))), button_labels = list(submit = structure(\"<span data-i18n=\\\"button.questionsubmit\\\">Submit Answer<\\u002fspan>\", html = TRUE, class = c(\"html\", \n    \"character\")), try_again = structure(\"<span data-i18n=\\\"button.questiontryagain\\\">Try Again<\\u002fspan>\", html = TRUE, class = c(\"html\", \n    \"character\"))), messages = list(correct = NULL, try_again = NULL, \n        incorrect = NULL, message = structure(\"Example correct answer: Surface type is related to ace rate, with grass having the highest rate, hard court being slightly lower, and clay being much lower.\", html = TRUE, class = c(\"html\", \n        \"character\")), post_message = NULL), ids = list(answer = \"conclusion_sport-answer\", \n        question = \"conclusion_sport\"), loading = NULL, random_answer_order = FALSE, \n    allow_retry = FALSE, seed = 1102142358.48677, options = list(\n        placeholder = \"Enter answer here...\", trim = TRUE, rows = 5)), class = c(\"learnr_text\", \n\"tutorial_question\")), session = session)\n</script>\n",
      "preserve528f708a257384a9": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\n`tutorial-exercise-anova-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-anova-code-editor`)), session)\noutput$`tutorial-exercise-anova-output` <- renderUI({\n  `tutorial-exercise-anova-result`()\n})\n</script>\n",
      "preserve5835ec57711b4f6b": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::question_prerendered_chunk(structure(list(type = \"learnr_radio\", label = \"output_B2\", question = structure(\"Which row of the Coefficients table in the output above corresponds to the average ace rate difference for clay versus grass surfaces?\", html = TRUE, class = c(\"html\", \n\"character\")), answers = list(structure(list(id = \"lnr_ans_8d40b4a\", \n    option = \"(Intercept) = 0.582\", value = \"(Intercept) = 0.582\", \n    label = structure(\"(Intercept) = 0.582\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_d4e569e\", \n    option = \"surfaceHard = -0.048\", value = \"surfaceHard = -0.048\", \n    label = structure(\"surfaceHard = -0.048\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_e98f334\", \n    option = \"surfaceClay = -0.250\", value = \"surfaceClay = -0.250\", \n    label = structure(\"surfaceClay = -0.250\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = TRUE, message = structure(\"This is the mean ace rate difference for hard court versus grass surfaces, so this must be β2!\", html = TRUE, class = c(\"html\", \n    \"character\")), type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\"))), button_labels = list(submit = structure(\"<span data-i18n=\\\"button.questionsubmit\\\">Submit Answer<\\u002fspan>\", html = TRUE, class = c(\"html\", \n\"character\")), try_again = structure(\"<span data-i18n=\\\"button.questiontryagain\\\">Try Again<\\u002fspan>\", html = TRUE, class = c(\"html\", \n\"character\"))), messages = list(correct = structure(\"Correct!\", html = TRUE, class = c(\"html\", \n\"character\")), try_again = structure(\"Incorrect\", html = TRUE, class = c(\"html\", \n\"character\")), incorrect = structure(\"Incorrect\", html = TRUE, class = c(\"html\", \n\"character\")), message = NULL, post_message = NULL), ids = list(\n    answer = \"output_B2-answer\", question = \"output_B2\"), loading = NULL, \n    random_answer_order = FALSE, allow_retry = TRUE, seed = 1497549240.80265, \n    options = list()), class = c(\"learnr_radio\", \"tutorial_question\"\n)), session = session)\n</script>\n",
      "preserve60c8481f69015496": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::question_prerendered_chunk(structure(list(type = \"learnr_text\", label = \"equation_q_B2\", \n    question = structure(\"In our model AceRate=β0 + β1<em>Hard + β2<\\u002fem>Clay + ε, β2 is the average difference in _______ for games on __________ versus _________. (The blanks can be more than one word.)\", html = TRUE, class = c(\"html\", \n    \"character\")), answers = list(structure(list(id = \"lnr_ans_9bad4fc\", \n        option = \"\", value = \"\", label = structure(\"\", html = TRUE, class = c(\"html\", \n        \"character\")), correct = TRUE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n    \"tutorial_quiz_answer\"))), button_labels = list(submit = structure(\"<span data-i18n=\\\"button.questionsubmit\\\">Submit Answer<\\u002fspan>\", html = TRUE, class = c(\"html\", \n    \"character\")), try_again = structure(\"<span data-i18n=\\\"button.questiontryagain\\\">Try Again<\\u002fspan>\", html = TRUE, class = c(\"html\", \n    \"character\"))), messages = list(correct = NULL, try_again = NULL, \n        incorrect = NULL, message = structure(\"Example correct answer: β2 is the average difference in <u>ace rate<\\u002fu> for games on <u>clay<\\u002fu> versus <u>grass<\\u002fu>.\", html = TRUE, class = c(\"html\", \n        \"character\")), post_message = NULL), ids = list(answer = \"equation_q_B2-answer\", \n        question = \"equation_q_B2\"), loading = NULL, random_answer_order = FALSE, \n    allow_retry = FALSE, seed = 515649936.759882, options = list(\n        placeholder = \"Enter answer here...\", trim = TRUE, rows = 5)), class = c(\"learnr_text\", \n\"tutorial_question\")), session = session)\n</script>\n",
      "preserve6e9fa9c2d6cef589": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\n`tutorial-exercise-mean_and_boxplots-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-mean_and_boxplots-code-editor`)), session)\noutput$`tutorial-exercise-mean_and_boxplots-output` <- renderUI({\n  `tutorial-exercise-mean_and_boxplots-result`()\n})\n</script>\n",
      "preserve81d607c0bdfdeb7e": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::register_http_handlers(session, metadata = NULL)\n</script>\n",
      "preserve83c4502521e36487": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::store_exercise_cache(structure(list(label = \"anova\", global_setup = structure(c(\"\", \n\"pacman::p_load(learnr, tidyverse, stats, knitr, gridExtra)\", \n\"  \", \"# match2023 <- read.csv(\\\"atp_matches_2023.csv\\\")\", \"#   \", \n\"# match2023_df <- match2023 %>%\", \"#     select(tourney_name, round, winner_name, loser_name, surface,w_ace,l_ace,w_SvGms,l_SvGms) %>%\", \n\"#     na.omit(match2023_df) %>% \", \"#     mutate(total_ServiceGames = w_SvGms + l_SvGms) %>%\", \n\"#     mutate(total_aces = (l_ace + w_ace),\", \"#            surface = factor(surface, levels = c(\\\"Grass\\\", \\\"Hard\\\", \\\"Clay\\\"))) %>% \", \n\"#   select(-w_ace, -l_ace, -w_SvGms, -l_SvGms) %>% \", \"#   filter(tourney_name != \\\"United Cup\\\") %>%  # Exclude United Cup, which is a country team tournament\", \n\"#   as_tibble()\", \"\", \"#write.csv(match2023_df, \\\"atp_matches_2023_analysis.csv\\\")\", \n\"\", \"match2023_df <- read.csv(\\\"atp_matches_2023_analysis.csv\\\") %>% \", \n\"  mutate(surface = factor(surface, levels = c(\\\"Grass\\\",\\\"Hard\\\", \\\"Clay\\\")))\", \n\"\", \"\", \"\"), chunk_opts = list(label = \"setup\", include = FALSE)), \n    setup = \" match2023_df <- match2023_df %>%\\n    mutate(ace_rate = total_aces/total_ServiceGames)\\nmatch2023_df$Hard <- ifelse(match2023_df$surface == \\\"Hard\\\", 1, 0)\\nmatch2023_df$Clay <- ifelse(match2023_df$surface == \\\"Clay\\\", 1, 0)\", \n    chunks = list(list(label = \"ace_rate_for_exer\", code = \" match2023_df <- match2023_df %>%\\n    mutate(ace_rate = total_aces/total_ServiceGames)\", \n        opts = list(label = \"\\\"ace_rate_for_exer\\\"\", include = \"FALSE\"), \n        engine = \"r\"), list(label = \"dummy_for_exer\", code = \"match2023_df$Hard <- ifelse(match2023_df$surface == \\\"Hard\\\", 1, 0)\\nmatch2023_df$Clay <- ifelse(match2023_df$surface == \\\"Clay\\\", 1, 0)\", \n        opts = list(label = \"\\\"dummy_for_exer\\\"\", include = \"FALSE\", \n            exercise.setup = \"\\\"ace_rate_for_exer\\\"\"), engine = \"r\"), \n        list(label = \"anova\", code = \"ace_surface_anova <- aov(ace_rate ~ surface, match2023_df)\\nanova(ace_surface_anova)\", \n            opts = list(label = \"\\\"anova\\\"\", exercise = \"TRUE\", \n                exercise.setup = \"\\\"dummy_for_exer\\\"\"), engine = \"r\")), \n    code_check = NULL, error_check = NULL, check = NULL, solution = NULL, \n    tests = NULL, options = list(eval = FALSE, echo = TRUE, results = \"markup\", \n        tidy = FALSE, tidy.opts = NULL, collapse = FALSE, prompt = FALSE, \n        comment = NA, highlight = FALSE, size = \"normalsize\", \n        background = \"#F7F7F7\", strip.white = TRUE, cache = 0, \n        cache.path = \"index_cache/html/\", cache.vars = NULL, \n        cache.lazy = TRUE, dependson = NULL, autodep = FALSE, \n        cache.rebuild = FALSE, fig.keep = \"high\", fig.show = \"asis\", \n        fig.align = \"default\", fig.path = \"index_files/figure-html/\", \n        dev = \"png\", dev.args = NULL, dpi = 192, fig.ext = \"png\", \n        fig.width = 7L, fig.height = 5L, fig.env = \"figure\", \n        fig.cap = NULL, fig.scap = NULL, fig.lp = \"fig:\", fig.subcap = NULL, \n        fig.pos = \"\", out.width = 672L, out.height = NULL, out.extra = NULL, \n        fig.retina = 2, external = TRUE, sanitize = FALSE, interval = 1, \n        aniopts = \"controls,loop\", warning = TRUE, error = FALSE, \n        message = TRUE, render = NULL, ref.label = NULL, child = NULL, \n        engine = \"r\", split = FALSE, include = TRUE, purl = TRUE, \n        fig.asp = NULL, fenced.echo = FALSE, ft.shadow = FALSE, \n        label = \"anova\", exercise = TRUE, exercise.setup = \"dummy_for_exer\", \n        original.params.src = \"r anova, exercise = TRUE, exercise.setup = \\\"dummy_for_exer\\\"\", \n        chunk.echo = FALSE, code = c(\"ace_surface_anova <- aov(ace_rate ~ surface, match2023_df)\", \n        \"anova(ace_surface_anova)\"), out.width.px = 672L, out.height.px = 480L, \n        params.src = \"r anova, exercise = TRUE, exercise.setup = \\\"dummy_for_exer\\\"\", \n        fig.num = 0, exercise.df_print = \"default\", exercise.checker = \"NULL\"), \n    engine = \"r\", version = \"4\"), class = c(\"r\", \"tutorial_exercise\"\n)))\n</script>\n",
      "preserve888eb921614ba764": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\n`tutorial-exercise-dummy-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-dummy-code-editor`)), session)\noutput$`tutorial-exercise-dummy-output` <- renderUI({\n  `tutorial-exercise-dummy-result`()\n})\n</script>\n",
      "preserve8a40e8327eebb2b6": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\n`tutorial-exercise-pairwise_anova-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-pairwise_anova-code-editor`)), session)\noutput$`tutorial-exercise-pairwise_anova-output` <- renderUI({\n  `tutorial-exercise-pairwise_anova-result`()\n})\n</script>\n",
      "preserve921bb52e0ab1db57": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::store_exercise_cache(structure(list(label = \"pairwise_anova\", global_setup = structure(c(\"\", \n\"pacman::p_load(learnr, tidyverse, stats, knitr, gridExtra)\", \n\"  \", \"# match2023 <- read.csv(\\\"atp_matches_2023.csv\\\")\", \"#   \", \n\"# match2023_df <- match2023 %>%\", \"#     select(tourney_name, round, winner_name, loser_name, surface,w_ace,l_ace,w_SvGms,l_SvGms) %>%\", \n\"#     na.omit(match2023_df) %>% \", \"#     mutate(total_ServiceGames = w_SvGms + l_SvGms) %>%\", \n\"#     mutate(total_aces = (l_ace + w_ace),\", \"#            surface = factor(surface, levels = c(\\\"Grass\\\", \\\"Hard\\\", \\\"Clay\\\"))) %>% \", \n\"#   select(-w_ace, -l_ace, -w_SvGms, -l_SvGms) %>% \", \"#   filter(tourney_name != \\\"United Cup\\\") %>%  # Exclude United Cup, which is a country team tournament\", \n\"#   as_tibble()\", \"\", \"#write.csv(match2023_df, \\\"atp_matches_2023_analysis.csv\\\")\", \n\"\", \"match2023_df <- read.csv(\\\"atp_matches_2023_analysis.csv\\\") %>% \", \n\"  mutate(surface = factor(surface, levels = c(\\\"Grass\\\",\\\"Hard\\\", \\\"Clay\\\")))\", \n\"\", \"\", \"\"), chunk_opts = list(label = \"setup\", include = FALSE)), \n    setup = \" match2023_df <- match2023_df %>%\\n    mutate(ace_rate = total_aces/total_ServiceGames)\\nmatch2023_df$Hard <- ifelse(match2023_df$surface == \\\"Hard\\\", 1, 0)\\nmatch2023_df$Clay <- ifelse(match2023_df$surface == \\\"Clay\\\", 1, 0)\", \n    chunks = list(list(label = \"ace_rate_for_exer\", code = \" match2023_df <- match2023_df %>%\\n    mutate(ace_rate = total_aces/total_ServiceGames)\", \n        opts = list(label = \"\\\"ace_rate_for_exer\\\"\", include = \"FALSE\"), \n        engine = \"r\"), list(label = \"dummy_for_exer\", code = \"match2023_df$Hard <- ifelse(match2023_df$surface == \\\"Hard\\\", 1, 0)\\nmatch2023_df$Clay <- ifelse(match2023_df$surface == \\\"Clay\\\", 1, 0)\", \n        opts = list(label = \"\\\"dummy_for_exer\\\"\", include = \"FALSE\", \n            exercise.setup = \"\\\"ace_rate_for_exer\\\"\"), engine = \"r\"), \n        list(label = \"pairwise_anova\", code = \"pairwise.t.test(match2023_df$ace_rate, match2023_df$surface, p.adj = \\\"none\\\")\", \n            opts = list(label = \"\\\"pairwise_anova\\\"\", exercise = \"TRUE\", \n                exercise.setup = \"\\\"dummy_for_exer\\\"\"), engine = \"r\")), \n    code_check = NULL, error_check = NULL, check = NULL, solution = NULL, \n    tests = NULL, options = list(eval = FALSE, echo = TRUE, results = \"markup\", \n        tidy = FALSE, tidy.opts = NULL, collapse = FALSE, prompt = FALSE, \n        comment = NA, highlight = FALSE, size = \"normalsize\", \n        background = \"#F7F7F7\", strip.white = TRUE, cache = 0, \n        cache.path = \"index_cache/html/\", cache.vars = NULL, \n        cache.lazy = TRUE, dependson = NULL, autodep = FALSE, \n        cache.rebuild = FALSE, fig.keep = \"high\", fig.show = \"asis\", \n        fig.align = \"default\", fig.path = \"index_files/figure-html/\", \n        dev = \"png\", dev.args = NULL, dpi = 192, fig.ext = \"png\", \n        fig.width = 7L, fig.height = 5L, fig.env = \"figure\", \n        fig.cap = NULL, fig.scap = NULL, fig.lp = \"fig:\", fig.subcap = NULL, \n        fig.pos = \"\", out.width = 672L, out.height = NULL, out.extra = NULL, \n        fig.retina = 2, external = TRUE, sanitize = FALSE, interval = 1, \n        aniopts = \"controls,loop\", warning = TRUE, error = FALSE, \n        message = TRUE, render = NULL, ref.label = NULL, child = NULL, \n        engine = \"r\", split = FALSE, include = TRUE, purl = TRUE, \n        fig.asp = NULL, fenced.echo = FALSE, ft.shadow = FALSE, \n        label = \"pairwise_anova\", exercise = TRUE, exercise.setup = \"dummy_for_exer\", \n        original.params.src = \"r pairwise_anova, exercise=TRUE, exercise.setup = \\\"dummy_for_exer\\\"\", \n        chunk.echo = FALSE, code = \"pairwise.t.test(match2023_df$ace_rate, match2023_df$surface, p.adj = \\\"none\\\")\", \n        out.width.px = 672L, out.height.px = 480L, params.src = \"r pairwise_anova, exercise=TRUE, exercise.setup = \\\"dummy_for_exer\\\"\", \n        fig.num = 0, exercise.df_print = \"default\", exercise.checker = \"NULL\"), \n    engine = \"r\", version = \"4\"), class = c(\"r\", \"tutorial_exercise\"\n)))\n</script>\n",
      "preserve9524f19b90f47a1e": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\n`tutorial-exercise-filter-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-filter-code-editor`)), session)\noutput$`tutorial-exercise-filter-output` <- renderUI({\n  `tutorial-exercise-filter-result`()\n})\n</script>\n",
      "preserve9937f8900b16281d": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::question_prerendered_chunk(structure(list(type = \"learnr_radio\", label = \"rows\", question = structure(\"What does each row represent?\", html = TRUE, class = c(\"html\", \n\"character\")), answers = list(structure(list(id = \"lnr_ans_8f5987a\", \n    option = \"One tennis tournament\", value = \"One tennis tournament\", \n    label = structure(\"One tennis tournament\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_6ba2049\", \n    option = \"One tennis match in a tournament\", value = \"One tennis match in a tournament\", \n    label = structure(\"One tennis match in a tournament\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = TRUE, message = structure(\"That’s right! One row corresponds to one tennis match, where one player plays another until winning and advancing in the tournament or losing. It is comprised of multiple sets, (service) games, points, and serves.\", html = TRUE, class = c(\"html\", \n    \"character\")), type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_b6cf8ed\", \n    option = \"One tennis serve\", value = \"One tennis serve\", \n    label = structure(\"One tennis serve\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_6aa0e9d\", \n    option = \"One player\", value = \"One player\", label = structure(\"One player\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\"))), button_labels = list(submit = structure(\"<span data-i18n=\\\"button.questionsubmit\\\">Submit Answer<\\u002fspan>\", html = TRUE, class = c(\"html\", \n\"character\")), try_again = structure(\"<span data-i18n=\\\"button.questiontryagain\\\">Try Again<\\u002fspan>\", html = TRUE, class = c(\"html\", \n\"character\"))), messages = list(correct = structure(\"Correct!\", html = TRUE, class = c(\"html\", \n\"character\")), try_again = structure(\"Incorrect\", html = TRUE, class = c(\"html\", \n\"character\")), incorrect = structure(\"Incorrect\", html = TRUE, class = c(\"html\", \n\"character\")), message = NULL, post_message = NULL), ids = list(\n    answer = \"rows-answer\", question = \"rows\"), loading = NULL, \n    random_answer_order = FALSE, allow_retry = TRUE, seed = 1934015658.5994, \n    options = list()), class = c(\"learnr_radio\", \"tutorial_question\"\n)), session = session)\n</script>\n",
      "preserve9c1d460de0f5d568": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\n`tutorial-exercise-head-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-head-code-editor`)), session)\noutput$`tutorial-exercise-head-output` <- renderUI({\n  `tutorial-exercise-head-result`()\n})\n</script>\n",
      "preservea0843bf44873cb1f": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::question_prerendered_chunk(structure(list(type = \"learnr_radio\", label = \"surf_diff\", question = structure(\"What surface looks to be most different from the others, and how so?\", html = TRUE, class = c(\"html\", \n\"character\")), answers = list(structure(list(id = \"lnr_ans_3a3a721\", \n    option = \"Clay, higher than the others\", value = \"Clay, higher than the others\", \n    label = structure(\"Clay, higher than the others\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_9f85acc\", \n    option = \"Clay, lower than the others\", value = \"Clay, lower than the others\", \n    label = structure(\"Clay, lower than the others\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = TRUE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_b8d1579\", \n    option = \"Grass, higher than the others\", value = \"Grass, higher than the others\", \n    label = structure(\"Grass, higher than the others\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_15b6331\", \n    option = \"Grass, lower than the others\", value = \"Grass, lower than the others\", \n    label = structure(\"Grass, lower than the others\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_7b36b4f\", \n    option = \"Hard Court, higher than the others\", value = \"Hard Court, higher than the others\", \n    label = structure(\"Hard Court, higher than the others\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_d467f53\", \n    option = \"Hard Course, lower than the others\", value = \"Hard Course, lower than the others\", \n    label = structure(\"Hard Course, lower than the others\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\"))), button_labels = list(submit = structure(\"<span data-i18n=\\\"button.questionsubmit\\\">Submit Answer<\\u002fspan>\", html = TRUE, class = c(\"html\", \n\"character\")), try_again = structure(\"<span data-i18n=\\\"button.questiontryagain\\\">Try Again<\\u002fspan>\", html = TRUE, class = c(\"html\", \n\"character\"))), messages = list(correct = structure(\"Correct!\", html = TRUE, class = c(\"html\", \n\"character\")), try_again = structure(\"Incorrect\", html = TRUE, class = c(\"html\", \n\"character\")), incorrect = structure(\"Incorrect\", html = TRUE, class = c(\"html\", \n\"character\")), message = NULL, post_message = NULL), ids = list(\n    answer = \"surf_diff-answer\", question = \"surf_diff\"), loading = NULL, \n    random_answer_order = FALSE, allow_retry = TRUE, seed = 2011656682.06325, \n    options = list()), class = c(\"learnr_radio\", \"tutorial_question\"\n)), session = session)\n</script>\n",
      "preservea4105c124e7b93c9": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::store_exercise_cache(structure(list(label = \"dummy\", global_setup = structure(c(\"\", \n\"pacman::p_load(learnr, tidyverse, stats, knitr, gridExtra)\", \n\"  \", \"# match2023 <- read.csv(\\\"atp_matches_2023.csv\\\")\", \"#   \", \n\"# match2023_df <- match2023 %>%\", \"#     select(tourney_name, round, winner_name, loser_name, surface,w_ace,l_ace,w_SvGms,l_SvGms) %>%\", \n\"#     na.omit(match2023_df) %>% \", \"#     mutate(total_ServiceGames = w_SvGms + l_SvGms) %>%\", \n\"#     mutate(total_aces = (l_ace + w_ace),\", \"#            surface = factor(surface, levels = c(\\\"Grass\\\", \\\"Hard\\\", \\\"Clay\\\"))) %>% \", \n\"#   select(-w_ace, -l_ace, -w_SvGms, -l_SvGms) %>% \", \"#   filter(tourney_name != \\\"United Cup\\\") %>%  # Exclude United Cup, which is a country team tournament\", \n\"#   as_tibble()\", \"\", \"#write.csv(match2023_df, \\\"atp_matches_2023_analysis.csv\\\")\", \n\"\", \"match2023_df <- read.csv(\\\"atp_matches_2023_analysis.csv\\\") %>% \", \n\"  mutate(surface = factor(surface, levels = c(\\\"Grass\\\",\\\"Hard\\\", \\\"Clay\\\")))\", \n\"\", \"\", \"\"), chunk_opts = list(label = \"setup\", include = FALSE)), \n    setup = NULL, chunks = list(list(label = \"dummy\", code = \"match2023_df$Hard <- ifelse(match2023_df$surface == \\\"Hard\\\", 1, 0)\\nmatch2023_df$Clay <- ifelse(match2023_df$surface == \\\"Clay\\\", 1, 0)\\nhead(match2023_df)\", \n        opts = list(label = \"\\\"dummy\\\"\", exercise = \"TRUE\"), \n        engine = \"r\")), code_check = NULL, error_check = NULL, \n    check = NULL, solution = NULL, tests = NULL, options = list(\n        eval = FALSE, echo = TRUE, results = \"markup\", tidy = FALSE, \n        tidy.opts = NULL, collapse = FALSE, prompt = FALSE, comment = NA, \n        highlight = FALSE, size = \"normalsize\", background = \"#F7F7F7\", \n        strip.white = TRUE, cache = 0, cache.path = \"index_cache/html/\", \n        cache.vars = NULL, cache.lazy = TRUE, dependson = NULL, \n        autodep = FALSE, cache.rebuild = FALSE, fig.keep = \"high\", \n        fig.show = \"asis\", fig.align = \"default\", fig.path = \"index_files/figure-html/\", \n        dev = \"png\", dev.args = NULL, dpi = 192, fig.ext = \"png\", \n        fig.width = 7L, fig.height = 5L, fig.env = \"figure\", \n        fig.cap = NULL, fig.scap = NULL, fig.lp = \"fig:\", fig.subcap = NULL, \n        fig.pos = \"\", out.width = 672L, out.height = NULL, out.extra = NULL, \n        fig.retina = 2, external = TRUE, sanitize = FALSE, interval = 1, \n        aniopts = \"controls,loop\", warning = TRUE, error = FALSE, \n        message = TRUE, render = NULL, ref.label = NULL, child = NULL, \n        engine = \"r\", split = FALSE, include = TRUE, purl = TRUE, \n        fig.asp = NULL, fenced.echo = FALSE, ft.shadow = FALSE, \n        label = \"dummy\", exercise = TRUE, original.params.src = \"r dummy, exercise=TRUE\", \n        chunk.echo = FALSE, code = c(\"match2023_df$Hard <- ifelse(match2023_df$surface == \\\"Hard\\\", 1, 0)\", \n        \"match2023_df$Clay <- ifelse(match2023_df$surface == \\\"Clay\\\", 1, 0)\", \n        \"head(match2023_df)\"), out.width.px = 672L, out.height.px = 480L, \n        params.src = \"r dummy, exercise=TRUE\", fig.num = 0, exercise.df_print = \"default\", \n        exercise.checker = \"NULL\"), engine = \"r\", version = \"4\"), class = c(\"r\", \n\"tutorial_exercise\")))\n</script>\n",
      "preservea60dd164550b139c": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::store_exercise_cache(structure(list(label = \"ace_rate\", global_setup = structure(c(\"\", \n\"pacman::p_load(learnr, tidyverse, stats, knitr, gridExtra)\", \n\"  \", \"# match2023 <- read.csv(\\\"atp_matches_2023.csv\\\")\", \"#   \", \n\"# match2023_df <- match2023 %>%\", \"#     select(tourney_name, round, winner_name, loser_name, surface,w_ace,l_ace,w_SvGms,l_SvGms) %>%\", \n\"#     na.omit(match2023_df) %>% \", \"#     mutate(total_ServiceGames = w_SvGms + l_SvGms) %>%\", \n\"#     mutate(total_aces = (l_ace + w_ace),\", \"#            surface = factor(surface, levels = c(\\\"Grass\\\", \\\"Hard\\\", \\\"Clay\\\"))) %>% \", \n\"#   select(-w_ace, -l_ace, -w_SvGms, -l_SvGms) %>% \", \"#   filter(tourney_name != \\\"United Cup\\\") %>%  # Exclude United Cup, which is a country team tournament\", \n\"#   as_tibble()\", \"\", \"#write.csv(match2023_df, \\\"atp_matches_2023_analysis.csv\\\")\", \n\"\", \"match2023_df <- read.csv(\\\"atp_matches_2023_analysis.csv\\\") %>% \", \n\"  mutate(surface = factor(surface, levels = c(\\\"Grass\\\",\\\"Hard\\\", \\\"Clay\\\")))\", \n\"\", \"\", \"\"), chunk_opts = list(label = \"setup\", include = FALSE)), \n    setup = NULL, chunks = list(list(label = \"ace_rate\", code = \" match2023_df <- match2023_df %>%\\n    mutate(ace_rate = total_aces/total_ServiceGames)\\n\\n# Look at the first 6 rows of the data with the new variable\\nhead(match2023_df)\", \n        opts = list(label = \"\\\"ace_rate\\\"\", exercise = \"TRUE\"), \n        engine = \"r\")), code_check = NULL, error_check = NULL, \n    check = NULL, solution = NULL, tests = NULL, options = list(\n        eval = FALSE, echo = TRUE, results = \"markup\", tidy = FALSE, \n        tidy.opts = NULL, collapse = FALSE, prompt = FALSE, comment = NA, \n        highlight = FALSE, size = \"normalsize\", background = \"#F7F7F7\", \n        strip.white = TRUE, cache = 0, cache.path = \"index_cache/html/\", \n        cache.vars = NULL, cache.lazy = TRUE, dependson = NULL, \n        autodep = FALSE, cache.rebuild = FALSE, fig.keep = \"high\", \n        fig.show = \"asis\", fig.align = \"default\", fig.path = \"index_files/figure-html/\", \n        dev = \"png\", dev.args = NULL, dpi = 192, fig.ext = \"png\", \n        fig.width = 7L, fig.height = 5L, fig.env = \"figure\", \n        fig.cap = NULL, fig.scap = NULL, fig.lp = \"fig:\", fig.subcap = NULL, \n        fig.pos = \"\", out.width = 672L, out.height = NULL, out.extra = NULL, \n        fig.retina = 2, external = TRUE, sanitize = FALSE, interval = 1, \n        aniopts = \"controls,loop\", warning = TRUE, error = FALSE, \n        message = TRUE, render = NULL, ref.label = NULL, child = NULL, \n        engine = \"r\", split = FALSE, include = TRUE, purl = TRUE, \n        fig.asp = NULL, fenced.echo = FALSE, ft.shadow = FALSE, \n        label = \"ace_rate\", exercise = TRUE, original.params.src = \"r ace_rate, exercise = TRUE\", \n        chunk.echo = FALSE, code = c(\" match2023_df <- match2023_df %>%\", \n        \"    mutate(ace_rate = total_aces/total_ServiceGames)\", \n        \"\", \"# Look at the first 6 rows of the data with the new variable\", \n        \"head(match2023_df)\"), out.width.px = 672L, out.height.px = 480L, \n        params.src = \"r ace_rate, exercise = TRUE\", fig.num = 0, \n        exercise.df_print = \"default\", exercise.checker = \"NULL\"), \n    engine = \"r\", version = \"4\"), class = c(\"r\", \"tutorial_exercise\"\n)))\n</script>\n",
      "preserved88461179afc1e3d": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::question_prerendered_chunk(structure(list(type = \"learnr_text\", label = \"conclusion_stats\", \n    question = structure(\"How did statistics help us answer this question? What methods did we use?\", html = TRUE, class = c(\"html\", \n    \"character\")), answers = list(structure(list(id = \"lnr_ans_f972f4f\", \n        option = \"\", value = \"\", label = structure(\"\", html = TRUE, class = c(\"html\", \n        \"character\")), correct = TRUE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n    \"tutorial_quiz_answer\"))), button_labels = list(submit = structure(\"<span data-i18n=\\\"button.questionsubmit\\\">Submit Answer<\\u002fspan>\", html = TRUE, class = c(\"html\", \n    \"character\")), try_again = structure(\"<span data-i18n=\\\"button.questiontryagain\\\">Try Again<\\u002fspan>\", html = TRUE, class = c(\"html\", \n    \"character\"))), messages = list(correct = NULL, try_again = NULL, \n        incorrect = NULL, message = structure(\"Example correct answer: We used linear regression with dummy variables to analyze how a categorical variable (surface) is associated with a cotninuous outcome (ace rate). This was equivalent to running an ANOVA analysis but provided additional information such as how different ace rates are on each surface, rather than just that they are or are not.\", html = TRUE, class = c(\"html\", \n        \"character\")), post_message = NULL), ids = list(answer = \"conclusion_stats-answer\", \n        question = \"conclusion_stats\"), loading = NULL, random_answer_order = FALSE, \n    allow_retry = FALSE, seed = 549517484.744111, options = list(\n        placeholder = \"Enter answer here...\", trim = TRUE, rows = 5)), class = c(\"learnr_text\", \n\"tutorial_question\")), session = session)\n</script>\n",
      "preserved94e14aa28feb0df": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::question_prerendered_chunk(structure(list(type = \"learnr_radio\", label = \"logicals3\", question = structure(\"What does <code>total_ServiceGames<\\u002fcode> represent?\", html = TRUE, class = c(\"html\", \n\"character\")), answers = list(structure(list(id = \"lnr_ans_bde6c4c\", \n    option = \"The number of aces in the match\", value = \"The number of aces in the match\", \n    label = structure(\"The number of aces in the match\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_96e0568\", \n    option = \"The number of service games in the match\", value = \"The number of service games in the match\", \n    label = structure(\"The number of service games in the match\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = TRUE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_a777c50\", \n    option = \"The number of service games in the tournament\", \n    value = \"The number of service games in the tournament\", \n    label = structure(\"The number of service games in the tournament\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_c50e9f9\", \n    option = \"The total number of serves in the match\", value = \"The total number of serves in the match\", \n    label = structure(\"The total number of serves in the match\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\"))), button_labels = list(submit = structure(\"<span data-i18n=\\\"button.questionsubmit\\\">Submit Answer<\\u002fspan>\", html = TRUE, class = c(\"html\", \n\"character\")), try_again = structure(\"<span data-i18n=\\\"button.questiontryagain\\\">Try Again<\\u002fspan>\", html = TRUE, class = c(\"html\", \n\"character\"))), messages = list(correct = structure(\"Correct!\", html = TRUE, class = c(\"html\", \n\"character\")), try_again = structure(\"Incorrect\", html = TRUE, class = c(\"html\", \n\"character\")), incorrect = structure(\"Incorrect\", html = TRUE, class = c(\"html\", \n\"character\")), message = NULL, post_message = NULL), ids = list(\n    answer = \"logicals3-answer\", question = \"logicals3\"), loading = NULL, \n    random_answer_order = FALSE, allow_retry = TRUE, seed = 563722438.737496, \n    options = list()), class = c(\"learnr_radio\", \"tutorial_question\"\n)), session = session)\n</script>\n",
      "preservedec69f3f293c6026": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::question_prerendered_chunk(structure(list(type = \"learnr_text\", label = \"mean_diffs_q\", \n    question = structure(\"What are the differences in ace rate per service game across surfaces?\", html = TRUE, class = c(\"html\", \n    \"character\")), answers = list(structure(list(id = \"lnr_ans_a86c1f\", \n        option = \"\", value = \"\", label = structure(\"\", html = TRUE, class = c(\"html\", \n        \"character\")), correct = TRUE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n    \"tutorial_quiz_answer\"))), button_labels = list(submit = structure(\"<span data-i18n=\\\"button.questionsubmit\\\">Submit Answer<\\u002fspan>\", html = TRUE, class = c(\"html\", \n    \"character\")), try_again = structure(\"<span data-i18n=\\\"button.questiontryagain\\\">Try Again<\\u002fspan>\", html = TRUE, class = c(\"html\", \n    \"character\"))), messages = list(correct = NULL, try_again = NULL, \n        incorrect = NULL, message = structure(\"Example correct answer: Grass is highest at 0.58 aces per service game. Hard court is about 0.05 lower than grass, and clay is 0.25 below grass.\", html = TRUE, class = c(\"html\", \n        \"character\")), post_message = NULL), ids = list(answer = \"mean_diffs_q-answer\", \n        question = \"mean_diffs_q\"), loading = NULL, random_answer_order = FALSE, \n    allow_retry = FALSE, seed = 1424731257.83656, options = list(\n        placeholder = \"Enter answer here...\", trim = TRUE, rows = 5)), class = c(\"learnr_text\", \n\"tutorial_question\")), session = session)\n</script>\n",
      "preservedf1b6629f3614250": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\n`tutorial-exercise-ace_rate-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-ace_rate-code-editor`)), session)\noutput$`tutorial-exercise-ace_rate-output` <- renderUI({\n  `tutorial-exercise-ace_rate-result`()\n})\n</script>\n",
      "preservee880261d95bfcb9c": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::question_prerendered_chunk(structure(list(type = \"learnr_radio\", label = \"logicals4\", question = structure(\"What does <code>total_aces<\\u002fcode> represent?\", html = TRUE, class = c(\"html\", \n\"character\")), answers = list(structure(list(id = \"lnr_ans_9d13099\", \n    option = \"The number of aces in the match\", value = \"The number of aces in the match\", \n    label = structure(\"The number of aces in the match\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = TRUE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_d189853\", \n    option = \"The number of service games in the match\", value = \"The number of service games in the match\", \n    label = structure(\"The number of service games in the match\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_8b21a01\", \n    option = \"The number of aces in the tournament\", value = \"The number of aces in the tournament\", \n    label = structure(\"The number of aces in the tournament\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\")), structure(list(id = \"lnr_ans_bd01c27\", \n    option = \"The total number of aces by the match's winner\", \n    value = \"The total number of aces by the match's winner\", \n    label = structure(\"The total number of aces by the match’s winner\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = FALSE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\"))), button_labels = list(submit = structure(\"<span data-i18n=\\\"button.questionsubmit\\\">Submit Answer<\\u002fspan>\", html = TRUE, class = c(\"html\", \n\"character\")), try_again = structure(\"<span data-i18n=\\\"button.questiontryagain\\\">Try Again<\\u002fspan>\", html = TRUE, class = c(\"html\", \n\"character\"))), messages = list(correct = structure(\"Correct!\", html = TRUE, class = c(\"html\", \n\"character\")), try_again = structure(\"Incorrect\", html = TRUE, class = c(\"html\", \n\"character\")), incorrect = structure(\"Incorrect\", html = TRUE, class = c(\"html\", \n\"character\")), message = NULL, post_message = NULL), ids = list(\n    answer = \"logicals4-answer\", question = \"logicals4\"), loading = NULL, \n    random_answer_order = FALSE, allow_retry = TRUE, seed = 1106106866.98493, \n    options = list()), class = c(\"learnr_radio\", \"tutorial_question\"\n)), session = session)\n</script>\n",
      "preserveebdc88855b0094de": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::question_prerendered_chunk(structure(list(type = \"learnr_text\", label = \"ace_rate_q\", question = structure(\"We will be analyzing matches of various lengths (that is, with varying numbers of games). Why might it be inappropriate to simply look at the number of aces in each match?\", html = TRUE, class = c(\"html\", \n\"character\")), answers = list(structure(list(id = \"lnr_ans_d920868\", \n    option = \"\", value = \"\", label = structure(\"\", html = TRUE, class = c(\"html\", \n    \"character\")), correct = TRUE, message = NULL, type = \"literal\"), class = c(\"tutorial_question_answer\", \n\"tutorial_quiz_answer\"))), button_labels = list(submit = structure(\"<span data-i18n=\\\"button.questionsubmit\\\">Submit Answer<\\u002fspan>\", html = TRUE, class = c(\"html\", \n\"character\")), try_again = structure(\"<span data-i18n=\\\"button.questiontryagain\\\">Try Again<\\u002fspan>\", html = TRUE, class = c(\"html\", \n\"character\"))), messages = list(correct = NULL, try_again = NULL, \n    incorrect = NULL, message = structure(\"Example correct answer: Longer matches have more chances for aces, naturally leading to more aces. But that’s obvious and not very interesting. So we will create a new variable adjusting for the length of matches, ace rate.\", html = TRUE, class = c(\"html\", \n    \"character\")), post_message = NULL), ids = list(answer = \"ace_rate_q-answer\", \n    question = \"ace_rate_q\"), loading = NULL, random_answer_order = FALSE, \n    allow_retry = FALSE, seed = 541391016.747895, options = list(\n        placeholder = \"Enter answer here...\", trim = TRUE, rows = 5)), class = c(\"learnr_text\", \n\"tutorial_question\")), session = session)\n</script>\n"
    },
    "postProcess": true
  }
}