project:
  type: website
  output-dir: docs
  render: 
    - "index.qmd"
    - "_team.qmd"
    - "*/*/index.qmd"
    - "by-statsds-topic.qmd"
    
website:
  google-analytics: "G-BNK257S380"
  cookie-consent:
    type: implied
    prefs-text: "Manage cookies"
  title: "West Point SCORE Module Preprint Repository"
  page-footer: 
    center:
      Maintained by All of Us! <br>
    
      We use cookies to track usage statistics 
      to help measure impact of the materials
      for authors. Please consider allowing 
      tracking cookies.
    
  navbar:
    left:
      - href: index.qmd
        text: Home
      - by-statsds-topic.qmd
      - href: _team.qmd
        text: West Point SCORE Team
      - href: https://modules.scorenetwork.org/
        text: SCORE Module Repository
      - href: https://data.scorenetwork.org/
        text: Data Repository
  sidebar:
    contents: auto
    collapse-level: 1


format:
  html:
    theme:
      - simplex
      - score.scss
    toc: true

execute:
  freeze: auto
